package ru.brobrocode.cadra.client.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "auth_type", // ignore manually set auth_type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the auth_type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "auth_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = MeApplicantProfile.class, name = "applicant"),
  @JsonSubTypes.Type(value = MeAnyProfile.class, name = "application"),
  @JsonSubTypes.Type(value = MeManagerProfile.class, name = "employer"),
  @JsonSubTypes.Type(value = MeEmployerProfile.class, name = "employer_integration"),
  @JsonSubTypes.Type(value = MeAnyProfile.class, name = "MeAnyProfile"),
  @JsonSubTypes.Type(value = MeApplicantProfile.class, name = "MeApplicantProfile"),
  @JsonSubTypes.Type(value = MeEmployerProfile.class, name = "MeEmployerProfile"),
  @JsonSubTypes.Type(value = MeManagerProfile.class, name = "MeManagerProfile")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
public interface MeProfile {
    public String getAuthType();
}
