/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.brobrocode.cadra.client.model.*;

import java.math.BigDecimal;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Комментарии к соискателю", description = "the Комментарии к соискателю API")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface ApplicantCommentsApi {

    /**
     * POST /applicant_comments/{applicant_id} : Добавление комментария
     * Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access)
     *
     * @param applicantId Идентификатор соискателя, который можно узнать из поля &#x60;owner&#x60; [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param text Текст комментария (required)
     * @param accessType Тип доступа. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле &#x60;applicant_comment_access_type&#x60; (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Комментарий добавлен (status code 201)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Получение комментариев недоступно для текущего пользователя (status code 403)
     *         or Указанный соискатель не найден (status code 404)
     */
    @Operation(
        operationId = "addApplicantComment",
        summary = "Добавление комментария",
        description = "Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access)",
        tags = { "Комментарии к соискателю", "Комментарии к соискателю на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Комментарий добавлен", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplicantCommentsApplicantCommentItem.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Получение комментариев недоступно для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный соискатель не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/applicant_comments/{applicant_id}",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<ApplicantCommentsApplicantCommentItem> addApplicantComment(
        @Parameter(name = "applicant_id", description = "Идентификатор соискателя, который можно узнать из поля `owner` [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field)", required = true, in = ParameterIn.PATH) @PathVariable("applicant_id") String applicantId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "text", description = "Текст комментария", required = true) @Valid @RequestParam(value = "text", required = true) String text,
        @Parameter(name = "access_type", description = "Тип доступа. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле `applicant_comment_access_type`", required = true) @Valid @RequestParam(value = "access_type", required = true) String accessType,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * DELETE /applicant_comments/{applicant_id}/{comment_id} : Удаление комментария
     * Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Удалить комментарий может только его автор 
     *
     * @param applicantId Идентификатор соискателя, который можно узнать из поля &#x60;owner&#x60; [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field) (required)
     * @param commentId Идентификатор комментария, который будет удален. Его можно узнать в [списке комментариев](#tag/Kommentarii-k-soiskatelyu/operation/get-applicant-comments-list) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ. Комментарий удален (status code 204)
     *         or Удаление комментария недоступно для текущего пользователя (status code 403)
     *         or Указанный соискатель не существует (status code 404)
     */
    @Operation(
        operationId = "deleteApplicantComment",
        summary = "Удаление комментария",
        description = "Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Удалить комментарий может только его автор ",
        tags = { "Комментарии к соискателю", "Комментарии к соискателю на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ. Комментарий удален"),
            @ApiResponse(responseCode = "403", description = "Удаление комментария недоступно для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный соискатель не существует", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/applicant_comments/{applicant_id}/{comment_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteApplicantComment(
        @Parameter(name = "applicant_id", description = "Идентификатор соискателя, который можно узнать из поля `owner` [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field)", required = true, in = ParameterIn.PATH) @PathVariable("applicant_id") String applicantId,
        @Parameter(name = "comment_id", description = "Идентификатор комментария, который будет удален. Его можно узнать в [списке комментариев](#tag/Kommentarii-k-soiskatelyu/operation/get-applicant-comments-list)", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") String commentId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /applicant_comments/{applicant_id} : Получение списка комментариев
     * Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Список будет содержать комментарии текущего пользователя, а также комментарии других менеджеров компании, если они открыли доступ к ним при публикации 
     *
     * @param applicantId Идентификатор соискателя, который можно узнать из поля &#x60;owner&#x60; [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (optional)
     * @param perPage Результатов на странице (optional)
     * @param orderBy Сортировка комментариев. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле &#x60;applicant_comments_order&#x60; (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Получение комментариев недоступно для текущего пользователя (status code 403)
     *         or Указанный соискатель не найден (status code 404)
     */
    @Operation(
        operationId = "getApplicantCommentsList",
        summary = "Получение списка комментариев",
        description = "Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Список будет содержать комментарии текущего пользователя, а также комментарии других менеджеров компании, если они открыли доступ к ним при публикации ",
        tags = { "Комментарии к соискателю", "Комментарии к соискателю на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplicantCommentsApplicantCommentsList.class))
            }),
            @ApiResponse(responseCode = "403", description = "Получение комментариев недоступно для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный соискатель не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/applicant_comments/{applicant_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ApplicantCommentsApplicantCommentsList> getApplicantCommentsList(
        @Parameter(name = "applicant_id", description = "Идентификатор соискателя, который можно узнать из поля `owner` [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field)", required = true, in = ParameterIn.PATH) @PathVariable("applicant_id") String applicantId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @Parameter(name = "per_page", description = "Результатов на странице", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false) BigDecimal perPage,
        @Parameter(name = "order_by", description = "Сортировка комментариев. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле `applicant_comments_order`", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /applicant_comments/{applicant_id}/{comment_id} : Обновление комментария
     * Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Автор комментария может изменить его текст и тип доступа. Если параметр не передан, то его значение останется прежним 
     *
     * @param applicantId Идентификатор соискателя, который можно узнать из поля &#x60;owner&#x60; [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field) (required)
     * @param commentId Идентификатор комментария, который можно узнать в [списке комментариев](#tag/Kommentarii-k-soiskatelyu/operation/get-applicant-comments-list) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param text Текст комментария (optional)
     * @param accessType Тип доступа. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле &#x60;applicant_comment_access_type&#x60; (optional)
     * @return Успешный ответ. Комментарий обновлен (status code 204)
     *         or Ошибка в параметрах запроса. Дополнительно могут быть указаны названия параметров с ошибками (status code 400)
     *         or Изменение комментария недоступно для текущего пользователя (status code 403)
     *         or Указанный соискатель или комментарий не существует (status code 404)
     */
    @Operation(
        operationId = "updateApplicantComment",
        summary = "Обновление комментария",
        description = "Метод требует наличия [платного доступа для работодателя](#tag/Uslugi-rabotodatelya/operation/get-payable-api-method-access).  Автор комментария может изменить его текст и тип доступа. Если параметр не передан, то его значение останется прежним ",
        tags = { "Комментарии к соискателю", "Комментарии к соискателю на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ. Комментарий обновлен"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса. Дополнительно могут быть указаны названия параметров с ошибками", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Изменение комментария недоступно для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный соискатель или комментарий не существует", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/applicant_comments/{applicant_id}/{comment_id}",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<Void> updateApplicantComment(
        @Parameter(name = "applicant_id", description = "Идентификатор соискателя, который можно узнать из поля `owner` [в резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#owner-field)", required = true, in = ParameterIn.PATH) @PathVariable("applicant_id") String applicantId,
        @Parameter(name = "comment_id", description = "Идентификатор комментария, который можно узнать в [списке комментариев](#tag/Kommentarii-k-soiskatelyu/operation/get-applicant-comments-list)", required = true, in = ParameterIn.PATH) @PathVariable("comment_id") String commentId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "text", description = "Текст комментария") @Valid @RequestParam(value = "text", required = false) String text,
        @Parameter(name = "access_type", description = "Тип доступа. Доступные значения перечислены [в справочнике](#tag/Obshie-spravochniki/operation/get-dictionaries) в поле `applicant_comment_access_type`") @Valid @RequestParam(value = "access_type", required = false) String accessType
    );

}
