/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.brobrocode.cadra.client.model.DictionariesAreaItem;
import ru.brobrocode.cadra.client.model.ErrorsDictionariesBadArgumentErrors;
import ru.brobrocode.cadra.client.model.IncludesArea;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Общие справочники", description = "Методы для получения справочной информации, независимые от авторизации")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface AreasApi {

    /**
     * GET /areas : Дерево всех регионов
     * Возвращает древовидный список всех регионов.  Значения в справочнике могут поменяться в любой момент 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param additionalCase Применимо только к русской локализации.  В дополнительном поле вернется название региона в указанном падеже. Поддерживается только значение &#x60;prepositional&#x60; — предложный падеж  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки в параметрах запроса (status code 400)
     */
    @Operation(
        operationId = "getAreas",
        summary = "Дерево всех регионов",
        description = "Возвращает древовидный список всех регионов.  Значения в справочнике могут поменяться в любой момент ",
        tags = { "Общие справочники" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = DictionariesAreaItem.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsDictionariesBadArgumentErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/areas",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<DictionariesAreaItem>> getAreas(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "additional_case", description = "Применимо только к русской локализации.  В дополнительном поле вернется название региона в указанном падеже. Поддерживается только значение `prepositional` — предложный падеж ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "additional_case", required = false) String additionalCase,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /areas/{area_id} : Справочник регионов, начиная с указанного
     * Возвращает древовидный список регионов, начиная с указанного.  Значения в справочнике могут поменяться в любой момент 
     *
     * @param areaId Идентификатор региона из справочника [/areas](#tag/Obshie-spravochniki/operation/get-areas) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param additionalCase Применимо только к русской локализации.  В дополнительном поле вернется название региона в указанном падеже. Поддерживается только значение &#x60;prepositional&#x60; — предложный падеж  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки в параметрах запроса (status code 400)
     */
    @Operation(
        operationId = "getAreasFromSpecified",
        summary = "Справочник регионов, начиная с указанного",
        description = "Возвращает древовидный список регионов, начиная с указанного.  Значения в справочнике могут поменяться в любой момент ",
        tags = { "Общие справочники" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DictionariesAreaItem.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsDictionariesBadArgumentErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/areas/{area_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<DictionariesAreaItem> getAreasFromSpecified(
        @Parameter(name = "area_id", description = "Идентификатор региона из справочника [/areas](#tag/Obshie-spravochniki/operation/get-areas)", required = true, in = ParameterIn.PATH) @PathVariable("area_id") String areaId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "additional_case", description = "Применимо только к русской локализации.  В дополнительном поле вернется название региона в указанном падеже. Поддерживается только значение `prepositional` — предложный падеж ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "additional_case", required = false) String additionalCase,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /areas/countries : Справочник стран
     * Возвращает подмножество регионов, являющихся странами
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     */
    @Operation(
        operationId = "getCountries",
        summary = "Справочник стран",
        description = "Возвращает подмножество регионов, являющихся странами",
        tags = { "Общие справочники" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = IncludesArea.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/areas/countries",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<IncludesArea>> getCountries(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
