/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import ru.brobrocode.cadra.client.model.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Работа с артефактами", description = "the Работа с артефактами API")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface ArtifactsApi {

    /**
     * DELETE /artifacts/{id} : Удаление артефакта
     *
     * @param id Идентификатор артефакта. Чтобы получить его, используйте метод [Получение портфолио](#tag/Rabota-s-artefaktami/operation/get-artifacts-portfolio) или [Получение фотографий](#tag/Rabota-s-artefaktami/operation/get-artifact-photos) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Текущий пользователь не является соискателем (status code 403)
     *         or Артефакт не существует или не принадлежит текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "deleteArtifact",
        summary = "Удаление артефакта",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Артефакт не существует или не принадлежит текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/artifacts/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteArtifact(
        @Parameter(name = "id", description = "Идентификатор артефакта. Чтобы получить его, используйте метод [Получение портфолио](#tag/Rabota-s-artefaktami/operation/get-artifacts-portfolio) или [Получение фотографий](#tag/Rabota-s-artefaktami/operation/get-artifact-photos)", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /artifacts/{id} : Редактирование артефакта
     * Метод позволяет отредактировать описание портфолио
     *
     * @param id Идентификатор артефакта. Чтобы получить его, используйте метод [Получение портфолио](#tag/Rabota-s-artefaktami/operation/get-artifacts-portfolio) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param description Описание изображения (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Текущий пользователь не является соискателем (status code 403)
     *         or Артефакт не существует или не принадлежит текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "editArtifact",
        summary = "Редактирование артефакта",
        description = "Метод позволяет отредактировать описание портфолио",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Артефакт не существует или не принадлежит текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/artifacts/{id}",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<Void> editArtifact(
        @Parameter(name = "id", description = "Идентификатор артефакта. Чтобы получить его, используйте метод [Получение портфолио](#tag/Rabota-s-artefaktami/operation/get-artifacts-portfolio)", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "description", description = "Описание изображения", required = true) @Valid @RequestParam(value = "description", required = true) String description,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /artifacts/photo : Получение фотографий
     * Возвращает список ранее загруженных изображений с фотографиями. Их можно использовать при создании/редактировании резюме
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "getArtifactPhotos",
        summary = "Получение фотографий",
        description = "Возвращает список ранее загруженных изображений с фотографиями. Их можно использовать при создании/редактировании резюме",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ArtifactsArtifactPhotoResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/artifacts/photo",
        produces = { "application/json" }
    )
    
    ResponseEntity<ArtifactsArtifactPhotoResponse> getArtifactPhotos(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /artifacts/photo/conditions : Условия загрузки фотографий
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "getArtifactPhotosConditions",
        summary = "Условия загрузки фотографий",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ArtifactsArtifactConditions.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/artifacts/photo/conditions",
        produces = { "application/json" }
    )
    
    ResponseEntity<ArtifactsArtifactConditions> getArtifactPhotosConditions(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /artifacts/portfolio : Получение портфолио
     * Возвращает список ранее загруженных изображений с портфолио. Их можно использовать при создании/редактировании резюме
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "getArtifactsPortfolio",
        summary = "Получение портфолио",
        description = "Возвращает список ранее загруженных изображений с портфолио. Их можно использовать при создании/редактировании резюме",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ArtifactsArtifactPortfolioResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/artifacts/portfolio",
        produces = { "application/json" }
    )
    
    ResponseEntity<ArtifactsArtifactPortfolioResponse> getArtifactsPortfolio(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /artifacts/portfolio/conditions : Условия загрузки портфолио
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "getArtifactsPortfolioConditions",
        summary = "Условия загрузки портфолио",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ArtifactsArtifactConditions.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/artifacts/portfolio/conditions",
        produces = { "application/json" }
    )
    
    ResponseEntity<ArtifactsArtifactConditions> getArtifactsPortfolioConditions(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * POST /artifacts : Загрузка артефакта
     * Запрос загружает файл с локальной машины в сервис.   Ограничения на типы файлов и их размер доступны в [условиях загрузки артефактов](#tag/Rabota-s-artefaktami).  Для прикрепления загруженных изображений в резюме, необходимо передать &#x60;id&#x60; артефакта в [соответствующее поле резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#resume-fields). Для удаления артефакта из резюме укажите &#x60;null&#x60; 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param file Файл изображения (required)
     * @param type Тип артефакта: &#x60;photo&#x60; или &#x60;portfolio&#x60; (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param description Текстовое описание. Имеет смысл для &#x60;portfolio&#x60; (optional)
     * @return Результат отправки файла (status code 201)
     *         or Ошибка в параметрах запроса или добавление изображения невозможно (status code 400)
     *         or Текущий пользователь не является соискателем (status code 403)
     *         or Изображение слишком большое (status code 413)
     */
    @Operation(
        operationId = "loadArtifact",
        summary = "Загрузка артефакта",
        description = "Запрос загружает файл с локальной машины в сервис.   Ограничения на типы файлов и их размер доступны в [условиях загрузки артефактов](#tag/Rabota-s-artefaktami).  Для прикрепления загруженных изображений в резюме, необходимо передать `id` артефакта в [соответствующее поле резюме](https://github.com/hhru/api/blob/master/docs/employer_resumes.md#resume-fields). Для удаления артефакта из резюме укажите `null` ",
        tags = { "Работа с артефактами" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Результат отправки файла", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ArtifactsArtifactItem.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса или добавление изображения невозможно", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsArtifactUploadBadJsonData.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "413", description = "Изображение слишком большое", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsRequestEntityTooLargeErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/artifacts",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<ArtifactsArtifactItem> loadArtifact(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "file", description = "Файл изображения", required = true) @RequestPart(value = "file", required = true) MultipartFile file,
        @Parameter(name = "type", description = "Тип артефакта: `photo` или `portfolio`", required = true) @Valid @RequestParam(value = "type", required = true) String type,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "description", description = "Текстовое описание. Имеет смысл для `portfolio`") @Valid @RequestParam(value = "description", required = false) String description
    );

}
