/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.brobrocode.cadra.client.model.ClickmeStatisticsResponse;
import ru.brobrocode.cadra.client.model.ErrorsCommonBadAuthorizationErrors;
import ru.brobrocode.cadra.client.model.ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Статистика рекламных кампаний в Clickme", description = "Получение информации о статистике рекламных кампаний в Clickme.  Clickme - это рекламная платформа, с помощью которой можно продвигать вакансии как на hh.ru, так и на внешних площадках. Подробнее про [Clickme](https://hh.ru/article/clickme) ")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface ClickmeApi {

    /**
     * GET /clickme/statistics : Получение информации о статистике рекламных кампаний в Clickme
     * Получение информации о статистике рекламных кампаний в Clickme
     *
     * @param dateFrom Дата, от которой нужно начать поиск. Значение указывается в формате [ISO 8601](#date-format) — &#x60;YYYY-MM-DD&#x60;  (required)
     * @param dateTo Дата, до которой нужно искать включительно. Значение указывается в формате [ISO 8601](#date-format) — &#x60;YYYY-MM-DD&#x60;  (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки в аргументах или в запросе (status code 400)
     *         or Недоступно для текущего пользователя (status code 403)
     */
    @Operation(
        operationId = "getClickmeStatistics",
        summary = "Получение информации о статистике рекламных кампаний в Clickme",
        description = "Получение информации о статистике рекламных кампаний в Clickme",
        tags = { "Статистика рекламных кампаний в Clickme" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClickmeStatisticsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки в аргументах или в запросе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Недоступно для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clickme/statistics",
        produces = { "application/json" }
    )
    
    ResponseEntity<ClickmeStatisticsResponse> getClickmeStatistics(
        @NotNull @Parameter(name = "date_from", description = "Дата, от которой нужно начать поиск. Значение указывается в формате [ISO 8601](#date-format) — `YYYY-MM-DD` ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_from", required = true) String dateFrom,
        @NotNull @Parameter(name = "date_to", description = "Дата, до которой нужно искать включительно. Значение указывается в формате [ISO 8601](#date-format) — `YYYY-MM-DD` ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_to", required = true) String dateTo,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
