/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.brobrocode.cadra.client.model.ErrorsCommonBadAuthorizationErrors;
import ru.brobrocode.cadra.client.model.ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors;
import ru.brobrocode.cadra.client.model.MeProfile;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Информация о соискателе", description = "Методы для просмотра информации об авторизованном соискателе")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface MeApi {

    /**
     * POST /me : Редактирование информации авторизованного пользователя
     * Редактирование ФИО или изменение флага «ищу работу». Данные можно редактировать только группами
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param firstName Имя (optional)
     * @param lastName Фамилия (optional)
     * @param middleName Отчество, поле может быть пустым (optional)
     * @param isInSearch Флаг «ищу работу». Возможные значения: &#x60;true&#x60;/&#x60;false&#x60; (optional)
     * @return Успешный ответ, данные переданы (status code 204)
     *         or Переданы не все поля, или параметры относятся к разным группам (status code 400)
     *         or Ошибка авторизации. Пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "editCurrentUserInfo",
        summary = "Редактирование информации авторизованного пользователя",
        description = "Редактирование ФИО или изменение флага «ищу работу». Данные можно редактировать только группами",
        tags = { "Информация о соискателе" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ, данные переданы"),
            @ApiResponse(responseCode = "400", description = "Переданы не все поля, или параметры относятся к разным группам", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации. Пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/me",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<Void> editCurrentUserInfo(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "first_name", description = "Имя") @Valid @RequestParam(value = "first_name", required = false) String firstName,
        @Parameter(name = "last_name", description = "Фамилия") @Valid @RequestParam(value = "last_name", required = false) String lastName,
        @Parameter(name = "middle_name", description = "Отчество, поле может быть пустым") @Valid @RequestParam(value = "middle_name", required = false) String middleName,
        @Parameter(name = "is_in_search", description = "Флаг «ищу работу». Возможные значения: `true`/`false`") @Valid @RequestParam(value = "is_in_search", required = false) String isInSearch
    );


    /**
     * GET /me : Информация о текущем пользователе
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибка авторизации (status code 403)
     */
    @Operation(
        operationId = "getCurrentUserInfo",
        summary = "Информация о текущем пользователе",
        tags = { "Информация о соискателе", "Информация о менеджере", "Информация о приложении", "Информация о работодателе", "Информация об интеграции работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MeProfile.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/me",
        produces = { "application/json" }
    )
    
    ResponseEntity<MeProfile> getCurrentUserInfo(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @NotNull @Parameter(name = "Authorization", description = "Токен", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Authorization", required = true) String token,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
