/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import feign.Headers;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.brobrocode.cadra.client.model.*;

import java.math.BigDecimal;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Вакансии", description = "the Вакансии API")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface NegotiationsApi {

    /**
     * POST /negotiations : Отклик на вакансию
     * Запрос позволяет пользователю откликнуться на вакансию.  Чтобы узнать, какими резюме возможно откликнуться на конкретную вакансию, воспользуйтесь [списком подходящих резюме](#tag/Rezyume.-Prosmotr-informacii/operation/get-suitable-resumes) 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param resumeId Идентификатор резюме, которым производится отклик (required)
     * @param vacancyId Идентификатор вакансии, на которую происходит отклик (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param message Сопроводительное письмо к отклику.  Является обязательным, если в вакансии указано, что обязательно сопроводительное письмо.  Максимальная длина — 10000 символов  (optional)
     * @return Результат отклика на обычную вакансию (status code 201)
     *         or Результат отклика на вакансию с прямым откликом (status code 303)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Невозможно откликнуться на вакансию (status code 403)
     */
    @Operation(
        operationId = "applyToVacancy",
        summary = "Отклик на вакансию",
        description = "Запрос позволяет пользователю откликнуться на вакансию.  Чтобы узнать, какими резюме возможно откликнуться на конкретную вакансию, воспользуйтесь [списком подходящих резюме](#tag/Rezyume.-Prosmotr-informacii/operation/get-suitable-resumes) ",
        tags = { "Вакансии" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Результат отклика на обычную вакансию", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "303", description = "Результат отклика на вакансию с прямым откликом", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ApplyToVacancy400Response.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApplyToVacancy400Response.class))
            }),
            @ApiResponse(responseCode = "403", description = "Невозможно откликнуться на вакансию", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsNegotiationNegotiationsBadAuthorizationErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationNegotiationsBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/negotiations",
        produces = { "text/html", "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<String> applyToVacancy(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @NotNull @Parameter(name = "Authorization", description = "Токен", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Authorization", required = true) String token,
        @Parameter(name = "resume_id", description = "Идентификатор резюме, которым производится отклик", required = true) @Valid @RequestParam(value = "resume_id", required = true) String resumeId,
        @Parameter(name = "vacancy_id", description = "Идентификатор вакансии, на которую происходит отклик", required = true) @Valid @RequestParam(value = "vacancy_id", required = true) String vacancyId,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "message", description = "Сопроводительное письмо к отклику.  Является обязательным, если в вакансии указано, что обязательно сопроводительное письмо.  Максимальная длина — 10000 символов ") @Valid @RequestParam(value = "message", required = false) String message
    );


    /**
     * PUT /negotiations/{collection_name}/{nid} : Действия по отклику/приглашению коллекции
     * Запрос изменяет состояние работодательского (&#x60;employer_state&#x60;) или соискательского (&#x60;state&#x60;) состояния отклика/приглашения.  #### Смена работодательского состояния отклика/приглашения  &gt; Доступные действия для каждого отклика/приглашения перечислены в массиве &#x60;employer_states&#x60; [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).   Чтобы изменить состояние отклика, выполните запрос из параметра &#x60;actions[].url&#x60; [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-collection-negotiations-list) для выбранного действия над откликом. В запросе необходимо передать аргументы массива &#x60;actions[].arguments&#x60; в формате &#x60;application/x-www-form-urlencoded&#x60;.  Примеры действий:  * отложить отклик; * пригласить соискателя на интервью в ответ на отклик; * отказать соискателю.  #### Смена соискательского состояния отклика/приглашения  Изменение соискательского состояния отклика/приглашения влияет на [статистику по работе с откликами](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations-statistics-employer).  Условие смены соискательского состояния отклика/приглашения — отправка сообщения соискателю любым из способов:  - Совершить действие с откликом/приглашением, используя метод &#x60;/negotiations/{collection_name}/{nid}&#x60;, с сопроводительным сообщением. - [Отправить сообщение](#tag/Otklikipriglasheniya-rabotodatelya/operation/send-negotiation-message) в отклике. Статус изменится, если перед отправкой использовался метод изменения работодательского статуса без сопроводительного сообщения.  Соискательский статус в обоих случаях изменится или на приглашение (&#x60;invitation&#x60;), или на отказ (&#x60;discard&#x60;) 
     *
     * @param collectionName Название коллекции. Возможные значения указаны в поле &#x60;collections[].id&#x60; [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations)  (required)
     * @param nid Идентификатор отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка параметров запроса (status code 400)
     *         or Невозможно выполнить действие по отклику/приглашению (status code 403)
     *         or Указанный отклик/приглашение не найден или у текущего пользователя нет доступа (status code 404)
     */
    @Operation(
        operationId = "changeNegotiationAction",
        summary = "Действия по отклику/приглашению коллекции",
        description = "Запрос изменяет состояние работодательского (`employer_state`) или соискательского (`state`) состояния отклика/приглашения.  #### Смена работодательского состояния отклика/приглашения  > Доступные действия для каждого отклика/приглашения перечислены в массиве `employer_states` [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).   Чтобы изменить состояние отклика, выполните запрос из параметра `actions[].url` [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-collection-negotiations-list) для выбранного действия над откликом. В запросе необходимо передать аргументы массива `actions[].arguments` в формате `application/x-www-form-urlencoded`.  Примеры действий:  * отложить отклик; * пригласить соискателя на интервью в ответ на отклик; * отказать соискателю.  #### Смена соискательского состояния отклика/приглашения  Изменение соискательского состояния отклика/приглашения влияет на [статистику по работе с откликами](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations-statistics-employer).  Условие смены соискательского состояния отклика/приглашения — отправка сообщения соискателю любым из способов:  - Совершить действие с откликом/приглашением, используя метод `/negotiations/{collection_name}/{nid}`, с сопроводительным сообщением. - [Отправить сообщение](#tag/Otklikipriglasheniya-rabotodatelya/operation/send-negotiation-message) в отклике. Статус изменится, если перед отправкой использовался метод изменения работодательского статуса без сопроводительного сообщения.  Соискательский статус в обоих случаях изменится или на приглашение (`invitation`), или на отказ (`discard`) ",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка параметров запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Невозможно выполнить действие по отклику/приглашению", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsVacancyApplyForbiddenErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный отклик/приглашение не найден или у текущего пользователя нет доступа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationNegotiationsNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/negotiations/{collection_name}/{nid}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> changeNegotiationAction(
        @Parameter(name = "collection_name", description = "Название коллекции. Возможные значения указаны в поле `collections[].id` [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) ", required = true, in = ParameterIn.PATH) @PathVariable("collection_name") String collectionName,
        @Parameter(name = "nid", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /negotiations/{nid}/messages/{mid} : Редактирование сообщения в отклике
     * На данный момент доступно редактирование только сообщения при отклике.   Текст сообщения можно редактировать после отправки при соблюдении следующих условий: - сообщение еще не прочитано другой стороной; - вакансия, на которую отправлялся отклик, должна быть активна (не в архиве);  - резюме из отклика не должно быть скрыто или удалено.   Условия могут измениться.  У каждого сообщения в [списке сообщений в отклике](https://github.com/hhru/api/blob/master/docs/negotiations.md#%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D0%B5) в поле &#x60;editable&#x60; указана возможность редактирования 
     *
     * @param nid Идентификатор отклика (required)
     * @param mid Идентификатор сообщения в отклике (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Выбранное сообщение не может быть отредактировано (status code 403)
     *         or Указанный отклик или сообщение не были найдены (status code 404)
     */
    @Operation(
        operationId = "editNegotiationMessage",
        summary = "Редактирование сообщения в отклике",
        description = "На данный момент доступно редактирование только сообщения при отклике.   Текст сообщения можно редактировать после отправки при соблюдении следующих условий: - сообщение еще не прочитано другой стороной; - вакансия, на которую отправлялся отклик, должна быть активна (не в архиве);  - резюме из отклика не должно быть скрыто или удалено.   Условия могут измениться.  У каждого сообщения в [списке сообщений в отклике](https://github.com/hhru/api/blob/master/docs/negotiations.md#%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B2-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D0%B5) в поле `editable` указана возможность редактирования ",
        tags = { "Переписка (отклики/приглашения) для соискателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Выбранное сообщение не может быть отредактировано", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationEditMessageForbiddenErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный отклик или сообщение не были найдены", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/negotiations/{nid}/messages/{mid}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> editNegotiationMessage(
        @Parameter(name = "nid", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @Parameter(name = "mid", description = "Идентификатор сообщения в отклике", required = true, in = ParameterIn.PATH) @PathVariable("mid") String mid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations/active : Список активных откликов
     * Возвращает список активных откликов соискателя.  Запрос является устаревшим и поддерживается для обратной совместимости. Вместо него используйте [запрос списка откликов](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiations) с параметром &#x60;?status&#x3D;active&#x60; 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (optional, default to 0)
     * @param perPage Количество элементов на странице (optional, default to 20)
     * @param orderBy Тип сортировки. Возможные значения указаны в поле &#x60;negotiations_order&#x60; [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries) (optional)
     * @param order Направление сортировки. Возможные значения: &#x60;asc&#x60; — по возрастанию, &#x60;desc&#x60; — по убыванию (optional)
     * @param vacancyId Фильтр по ID вакансии (optional)
     * @param hasUpdates Если передан &#x60;true&#x60;, запрос вернет только те отклики, для которых есть непросмотренные сообщения. По умолчанию &#x60;false&#x60;  (optional)
     * @param withJobSearchStatus Если передан &#x60;true&#x60;, запрос вернет статус поиска работы кандидатом  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибка параметров запроса (status code 400)
     *         or Текущий пользователь не является соискателем (status code 403)
     * @deprecated
     */
    @Deprecated
    @Operation(
        operationId = "getActiveNegotiations",
        summary = "Список активных откликов",
        description = "Возвращает список активных откликов соискателя.  Запрос является устаревшим и поддерживается для обратной совместимости. Вместо него используйте [запрос списка откликов](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiations) с параметром `?status=active` ",
        deprecated = true,
        tags = { "Переписка (отклики/приглашения) для соискателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsListResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка параметров запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations/active",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsListResponse> getActiveNegotiations(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") BigDecimal page,
        @Parameter(name = "per_page", description = "Количество элементов на странице", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false, defaultValue = "20") BigDecimal perPage,
        @Parameter(name = "order_by", description = "Тип сортировки. Возможные значения указаны в поле `negotiations_order` [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "order", description = "Направление сортировки. Возможные значения: `asc` — по возрастанию, `desc` — по убыванию", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order", required = false) String order,
        @Parameter(name = "vacancy_id", description = "Фильтр по ID вакансии", in = ParameterIn.QUERY) @Valid @RequestParam(value = "vacancy_id", required = false) String vacancyId,
        @Parameter(name = "has_updates", description = "Если передан `true`, запрос вернет только те отклики, для которых есть непросмотренные сообщения. По умолчанию `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "has_updates", required = false) Boolean hasUpdates,
        @Parameter(name = "with_job_search_status", description = "Если передан `true`, запрос вернет статус поиска работы кандидатом ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "with_job_search_status", required = false) Boolean withJobSearchStatus,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations/response : Список откликов/приглашений коллекции
     * Возвращает список откликов/приглашений для заданной коллекции. URL для запроса необходимо брать из поля &#x60;collections[].url&#x60; [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).  &gt; Вместо &#x60;response&#x60; необходимо указывать параметр &#x60;{collection_name}&#x60; — название коллекции. Возможные значения указаны в поле &#x60;collections[].id&#x60; [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).  В ответе будет только основная информация о резюме. Чтобы получить дополнительную информацию, например, контактный телефон, необходимо [запросить полное резюме](#tag/Upravlenie-vakansiyami/operation/get-vacancy).  Некоторые параметры запроса могут принимать множественные значения: &#x60;key&#x3D;value&amp;key&#x3D;value&#x60;. Если параметр может принимать несколько значений, об этом явно указано в его описании. Неизвестные параметры и параметры с ошибкой в названии игнорируются.  &gt; Коллекция &#x60;phone_calls&#x60; принимает только параметры &#x60;vacancy_id&#x60;, &#x60;order_by&#x60;, &#x60;page&#x60; и &#x60;per_page&#x60; 
     *
     * @param vacancyId Идентификатор вакансии (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param orderBy Тип сортировки. Возможные значения указаны в поле &#x60;order_types&#x60; [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations)  (optional)
     * @param page Порядковый номер страницы в выдаче. Поддерживаются [стандартные параметры пагинации](#section/Obshaya-informaciya/Paginaciya). По умолчанию нумерация начинается с 0 страницы  (optional, default to 0)
     * @param perPage Количество элементов на странице выдачи. Поддерживаются [стандартные параметры пагинации](#section/Obshaya-informaciya/Paginaciya). Максимальное значение — &#x60;50&#x60;  (optional, default to 20)
     * @param ageFrom Нижняя граница возраста соискателя в годах (optional)
     * @param ageTo Верхняя граница возраста соискателя в годах (optional)
     * @param area Регион. Возможные значения указаны в [справочнике регионов](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений.  По умолчанию выбираются резюме, в которых соискатели живут в указанных регионах или готовы в них переехать. Поменять это поведение поиска можно, указав параметр &#x60;relocation&#x60;  (optional)
     * @param citizenship Страна гражданства соискателя. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений  (optional)
     * @param currency Код валюты. Возможные значения перечислены в поле &#x60;currency.code&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  (optional)
     * @param driverLicenseTypes Категории водительских прав соискателя. Возможные значения перечислены в поле &#x60;driver_license_types&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param educationalInstitution Учебные заведения соискателя. В качестве параметров используются [подсказки по названиям университетов](#tag/Podskazki/operation/get-educational-institutions-suggests). Можно указать несколько значений  (optional)
     * @param educationLevel Уровень образования. Возможные значения перечислены в поле &#x60;education_level&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Если параметр не указан, поиск ведется без ограничений на уровень образования  (optional)
     * @param experience Опыт работы. Возможные значения перечислены в поле &#x60;experience&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param gender Пол соискателя. Возможные значения перечислены в поле &#x60;gender&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries).  По умолчанию вне зависимости от значения параметра будут найдены резюме, в которых пол не указан, исключить из поисковой выдачи такие резюме можно с помощью параметра &#x60;label&#x3D;only_with_gender&#x60;  (optional)
     * @param language Знание языка. Можно указать несколько значений. Задается в формате &#x60;language.level&#x60;, где:  * &#x60;language&#x60; — значение из [справочника языков](#tag/Obshie-spravochniki/operation/get-languages); * &#x60;level&#x60; — значение поля language_level из [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  Например, &#x60;ita.c2&#x60;  (optional)
     * @param relocation Готовность к переезду. Возможные значения указаны в поле &#x60;resume_search_relocation&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Необходимо указывать вместе с параметром &#x60;area&#x60;  (optional)
     * @param salaryFrom Нижняя граница желаемой заработной платы (ЗП) (optional)
     * @param salaryTo Верхняя граница желаемой заработной платы (ЗП) (optional)
     * @param searchRadiusMeters Расстояние до кандидата (в метрах) (optional)
     * @param searchText Поисковая строка (optional)
     * @param showOnlyNewResponses Показывать только непросмотренные отклики коллекции «Все неразобранные» (&#x60;/response&#x60;)  (optional)
     * @param showOnlyWithVehicle Показывать соискателей с личным автомобилем (optional)
     * @param showOnlyNew Показывать только отклики, в которых есть непрочитанные сообщения для всех коллекций, кроме «Все неразобранные» (&#x60;/response&#x60;)  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Текущий пользователь не является работодателем или не имеет доступа к методу (status code 403)
     *         or Запрашиваемая вакансия не существует или недоступна для текущего пользователя (status code 404)
     */
    @Operation(
        operationId = "getCollectionNegotiationsList",
        summary = "Список откликов/приглашений коллекции",
        description = "Возвращает список откликов/приглашений для заданной коллекции. URL для запроса необходимо брать из поля `collections[].url` [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).  > Вместо `response` необходимо указывать параметр `{collection_name}` — название коллекции. Возможные значения указаны в поле `collections[].id` [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations).  В ответе будет только основная информация о резюме. Чтобы получить дополнительную информацию, например, контактный телефон, необходимо [запросить полное резюме](#tag/Upravlenie-vakansiyami/operation/get-vacancy).  Некоторые параметры запроса могут принимать множественные значения: `key=value&key=value`. Если параметр может принимать несколько значений, об этом явно указано в его описании. Неизвестные параметры и параметры с ошибкой в названии игнорируются.  > Коллекция `phone_calls` принимает только параметры `vacancy_id`, `order_by`, `page` и `per_page` ",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsCollectionNegotiationsResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем или не имеет доступа к методу", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationCommonAndPaymentMethodError.class))
            }),
            @ApiResponse(responseCode = "404", description = "Запрашиваемая вакансия не существует или недоступна для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations/response",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsCollectionNegotiationsResponse> getCollectionNegotiationsList(
        @NotNull @Parameter(name = "vacancy_id", description = "Идентификатор вакансии", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "vacancy_id", required = true) String vacancyId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "order_by", description = "Тип сортировки. Возможные значения указаны в поле `order_types` [списка коллекций](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "page", description = "Порядковый номер страницы в выдаче. Поддерживаются [стандартные параметры пагинации](#section/Obshaya-informaciya/Paginaciya). По умолчанию нумерация начинается с 0 страницы ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Parameter(name = "per_page", description = "Количество элементов на странице выдачи. Поддерживаются [стандартные параметры пагинации](#section/Obshaya-informaciya/Paginaciya). Максимальное значение — `50` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false, defaultValue = "20") Integer perPage,
        @Parameter(name = "age_from", description = "Нижняя граница возраста соискателя в годах", in = ParameterIn.QUERY) @Valid @RequestParam(value = "age_from", required = false) String ageFrom,
        @Parameter(name = "age_to", description = "Верхняя граница возраста соискателя в годах", in = ParameterIn.QUERY) @Valid @RequestParam(value = "age_to", required = false) String ageTo,
        @Parameter(name = "area", description = "Регион. Возможные значения указаны в [справочнике регионов](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений.  По умолчанию выбираются резюме, в которых соискатели живут в указанных регионах или готовы в них переехать. Поменять это поведение поиска можно, указав параметр `relocation` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "area", required = false) String area,
        @Parameter(name = "citizenship", description = "Страна гражданства соискателя. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "citizenship", required = false) String citizenship,
        @Parameter(name = "currency", description = "Код валюты. Возможные значения перечислены в поле `currency.code` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "currency", required = false) String currency,
        @Parameter(name = "driver_license_types", description = "Категории водительских прав соискателя. Возможные значения перечислены в поле `driver_license_types` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "driver_license_types", required = false) String driverLicenseTypes,
        @Parameter(name = "educational_institution", description = "Учебные заведения соискателя. В качестве параметров используются [подсказки по названиям университетов](#tag/Podskazki/operation/get-educational-institutions-suggests). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "educational_institution", required = false) String educationalInstitution,
        @Parameter(name = "education_level", description = "Уровень образования. Возможные значения перечислены в поле `education_level` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Если параметр не указан, поиск ведется без ограничений на уровень образования ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "education_level", required = false) String educationLevel,
        @Parameter(name = "experience", description = "Опыт работы. Возможные значения перечислены в поле `experience` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "experience", required = false) String experience,
        @Parameter(name = "gender", description = "Пол соискателя. Возможные значения перечислены в поле `gender` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries).  По умолчанию вне зависимости от значения параметра будут найдены резюме, в которых пол не указан, исключить из поисковой выдачи такие резюме можно с помощью параметра `label=only_with_gender` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "gender", required = false) String gender,
        @Parameter(name = "language", description = "Знание языка. Можно указать несколько значений. Задается в формате `language.level`, где:  * `language` — значение из [справочника языков](#tag/Obshie-spravochniki/operation/get-languages); * `level` — значение поля language_level из [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  Например, `ita.c2` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "language", required = false) String language,
        @Parameter(name = "relocation", description = "Готовность к переезду. Возможные значения указаны в поле `resume_search_relocation` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Необходимо указывать вместе с параметром `area` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "relocation", required = false) String relocation,
        @Parameter(name = "salary_from", description = "Нижняя граница желаемой заработной платы (ЗП)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "salary_from", required = false) BigDecimal salaryFrom,
        @Parameter(name = "salary_to", description = "Верхняя граница желаемой заработной платы (ЗП)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "salary_to", required = false) BigDecimal salaryTo,
        @Parameter(name = "search_radius_meters", description = "Расстояние до кандидата (в метрах)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search_radius_meters", required = false) BigDecimal searchRadiusMeters,
        @Parameter(name = "search_text", description = "Поисковая строка", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search_text", required = false) String searchText,
        @Parameter(name = "show_only_new_responses", description = "Показывать только непросмотренные отклики коллекции «Все неразобранные» (`/response`) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "show_only_new_responses", required = false) Boolean showOnlyNewResponses,
        @Parameter(name = "show_only_with_vehicle", description = "Показывать соискателей с личным автомобилем", in = ParameterIn.QUERY) @Valid @RequestParam(value = "show_only_with_vehicle", required = false) Boolean showOnlyWithVehicle,
        @Parameter(name = "show_only_new", description = "Показывать только отклики, в которых есть непрочитанные сообщения для всех коллекций, кроме «Все неразобранные» (`/response`) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "show_only_new", required = false) Boolean showOnlyNew,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations/{id} : Просмотр отклика/приглашения
     * Запрос возвращает информацию об отклике/приглашении по его ID.  Работодатель может получить URL для запроса из [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-collection-negotiations-list) (поле &#x60;items[].url&#x60;).  &gt; !! Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться 
     *
     * @param id Идентификатор отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Отклик/приглашение получено (status code 200)
     *         or Текущий пользователь не является работодателем (status code 403)
     *         or Указанный отклик/приглашение не найден или у текущего пользователя нет доступа (status code 404)
     */
    @Operation(
        operationId = "getNegotiationItem",
        summary = "Просмотр отклика/приглашения",
        description = "Запрос возвращает информацию об отклике/приглашении по его ID.  Работодатель может получить URL для запроса из [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-collection-negotiations-list) (поле `items[].url`).  > !! Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться ",
        tags = { "Переписка (отклики/приглашения) для соискателя", "Отклики/приглашения работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Отклик/приглашение получено", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsNegotiationGetResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный отклик/приглашение не найден или у текущего пользователя нет доступа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationNegotiationsNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsNegotiationGetResponse> getNegotiationItem(
        @Parameter(name = "id", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations/{nid}/messages : Просмотр списка сообщений в отклике/приглашении
     * Запрос возвращает список всех сообщений выбранного отклика/приглашения. Работодатель может посмотреть список по URL, указанному в поле &#x60;messages&#x60; [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) или в [отдельном отклике](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-item).  Типы сообщений:  * сопроводительное письмо соискателя; * сопроводительное письмо работодателя при смене статуса отклика; * свободная переписка между соискателем и работодателем.  ‼️ Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и    [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться.   В связи с этим переписка может некорректно отображаться 
     *
     * @param nid Идентификатор отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param withTextOnly Вернуть непустые сообщения (содержат текст в параметре &#x60;text&#x60;) (optional, default to false)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     */
    @Operation(
        operationId = "getNegotiationMessages",
        summary = "Просмотр списка сообщений в отклике/приглашении",
        description = "Запрос возвращает список всех сообщений выбранного отклика/приглашения. Работодатель может посмотреть список по URL, указанному в поле `messages` [списка откликов/приглашений](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) или в [отдельном отклике](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-item).  Типы сообщений:  * сопроводительное письмо соискателя; * сопроводительное письмо работодателя при смене статуса отклика; * свободная переписка между соискателем и работодателем.  ‼️ Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и    [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться.   В связи с этим переписка может некорректно отображаться ",
        tags = { "Переписка (отклики/приглашения) для соискателя", "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsMessagesGetResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations/{nid}/messages",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsMessagesGetResponse> getNegotiationMessages(
        @Parameter(name = "nid", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "with_text_only", description = "Вернуть непустые сообщения (содержат текст в параметре `text`)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "with_text_only", required = false, defaultValue = "false") Boolean withTextOnly,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations/{nid}/test/solution : Получить результаты тестов, прикрепленных к вакансии
     * Запрос возвращает информацию о пройденных тестах откликнувшегося соискателя
     *
     * @param nid Идентификатор отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является работодателем (status code 403)
     *         or Указанный отклик/приглашение не найден или у текущего пользователя нет доступа (status code 404)
     */
    @Operation(
        operationId = "getNegotiationTestResults",
        summary = "Получить результаты тестов, прикрепленных к вакансии",
        description = "Запрос возвращает информацию о пройденных тестах откликнувшегося соискателя",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsNegotiationTestResultsResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный отклик/приглашение не найден или у текущего пользователя нет доступа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations/{nid}/test/solution",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsNegotiationTestResultsResponse> getNegotiationTestResults(
        @Parameter(name = "nid", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /negotiations : Список откликов/приглашений
     * Возвращает список откликов соискателя или список коллекций откликов/приглашений по [вакансии](#tag/Upravlenie-vakansiyami/operation/get-active-vacancy-list) работодателя.  По умолчанию отклики сортируются по дате последнего обновления — от новых к старым.  Чтобы получить список активных откликов, передайте в запросе параметр &#x60;?status&#x3D;active&#x60; 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (optional, default to 0)
     * @param perPage Количество элементов на странице (optional, default to 20)
     * @param orderBy Тип сортировки. Возможные значения указаны в поле &#x60;negotiations_order&#x60; [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries) (optional)
     * @param order Направление сортировки. Возможные значения: &#x60;asc&#x60; — по возрастанию, &#x60;desc&#x60; — по убыванию (optional)
     * @param vacancyId Фильтр по ID вакансии. Обязательный для работодателя (optional)
     * @param status Запрос вернет только те отклики, которые находятся в определенном статусе.  Возможные значения указаны в поле &#x60;applicant_negotiation_status&#x60; [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  (optional)
     * @param hasUpdates Если передан &#x60;true&#x60;, запрос вернет только те отклики, для которых есть непросмотренные сообщения. По умолчанию &#x60;false&#x60;  (optional)
     * @param withJobSearchStatus Если передан &#x60;true&#x60;, запрос вернет статус поиска работы кандидатом  (optional)
     * @param withGeneratedCollections Если передан &#x60;true&#x60;, запрос вернет информацию по [сгенерированным коллекциям](https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#term-collection) откликов/приглашений для данной вакансии.  Чтобы получить выгрузку по нескольким коллекциям, запросите их последовательно. По умолчанию &#x60;false&#x60;  (optional, default to false)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибка параметров запроса (status code 400)
     *         or Текущий пользователь не является соискателем (status code 403)
     *         or Указанная вакансия не существует или у текущего пользователя нет доступа (status code 404)
     */
    @Operation(
        operationId = "getNegotiations",
        summary = "Список откликов/приглашений",
        description = "Возвращает список откликов соискателя или список коллекций откликов/приглашений по [вакансии](#tag/Upravlenie-vakansiyami/operation/get-active-vacancy-list) работодателя.  По умолчанию отклики сортируются по дате последнего обновления — от новых к старым.  Чтобы получить список активных откликов, передайте в запросе параметр `?status=active` ",
        tags = { "Переписка (отклики/приглашения) для соискателя", "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsListResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка параметров запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанная вакансия не существует или у текущего пользователя нет доступа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/negotiations",
        produces = { "application/json" }
    )
    
    ResponseEntity<NegotiationsListResponse> getNegotiations(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") int page,
        @Parameter(name = "per_page", description = "Количество элементов на странице", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false, defaultValue = "20") int perPage,
        @Parameter(name = "order_by", description = "Тип сортировки. Возможные значения указаны в поле `negotiations_order` [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "order", description = "Направление сортировки. Возможные значения: `asc` — по возрастанию, `desc` — по убыванию", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order", required = false) String order,
        @Parameter(name = "vacancy_id", description = "Фильтр по ID вакансии. Обязательный для работодателя", in = ParameterIn.QUERY) @Valid @RequestParam(value = "vacancy_id", required = false) String vacancyId,
        @Parameter(name = "status", description = "Запрос вернет только те отклики, которые находятся в определенном статусе.  Возможные значения указаны в поле `applicant_negotiation_status` [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) String status,
        @Parameter(name = "has_updates", description = "Если передан `true`, запрос вернет только те отклики, для которых есть непросмотренные сообщения. По умолчанию `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "has_updates", required = false) Boolean hasUpdates,
        @Parameter(name = "with_job_search_status", description = "Если передан `true`, запрос вернет статус поиска работы кандидатом ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "with_job_search_status", required = false) Boolean withJobSearchStatus,
        @Parameter(name = "with_generated_collections", description = "Если передан `true`, запрос вернет информацию по [сгенерированным коллекциям](https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#term-collection) откликов/приглашений для данной вакансии.  Чтобы получить выгрузку по нескольким коллекциям, запросите их последовательно. По умолчанию `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "with_generated_collections", required = false, defaultValue = "false") Boolean withGeneratedCollections,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * DELETE /negotiations/active/{nid} : Скрыть отклик
     *
     * @param nid Идентификатор отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param withDeclineMessage Должно ли быть отправлено работодателю сообщение об отказе, по умолчанию &#x60;false&#x60;. Возможность отправить сообщение об отказе определяется полем &#x60;decline_allowed&#x60; получаемым при запросе [списка откликов или одного отклика](https://github.com/hhru/api/blob/e2a0ac4e174a6b56272f78348c05958f5db1b392/docs/negotiations.md#get_negotiation)  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Невозможно отправить сообщение об отказе (status code 403)
     *         or Отклик не существует (status code 404)
     *         or Чат отклика еще не готов (status code 425)
     */
    @Operation(
        operationId = "hideActiveResponse",
        summary = "Скрыть отклик",
        tags = { "Переписка (отклики/приглашения) для соискателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Невозможно отправить сообщение об отказе", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationHideResponseForbiddenErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Отклик не существует", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            }),
            @ApiResponse(responseCode = "425", description = "Чат отклика еще не готов", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationHideResponseErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/negotiations/active/{nid}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> hideActiveResponse(
        @Parameter(name = "nid", description = "Идентификатор отклика", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "with_decline_message", description = "Должно ли быть отправлено работодателю сообщение об отказе, по умолчанию `false`. Возможность отправить сообщение об отказе определяется полем `decline_allowed` получаемым при запросе [списка откликов или одного отклика](https://github.com/hhru/api/blob/e2a0ac4e174a6b56272f78348c05958f5db1b392/docs/negotiations.md#get_negotiation) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "with_decline_message", required = false) Boolean withDeclineMessage,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * POST /negotiations/phone_interview : Пригласить соискателя на вакансию
     * Запрос формирует приглашение на вакансию для соискателя по инициативе работодателя.  &gt; Вместо &#x60;phone_interview&#x60; необходимо сформировать запрос из параметра &#x60;negotiations_actions[].url&#x60; [списка подходящих вакансий к резюме](#tag/Upravlenie-vakansiyami/operation/get-active-vacancy-list), передав аргументы из массива &#x60;negotiations_actions[].arguments&#x60;.  Пример запроса:  &#x60;&#x60;&#x60; POST /negotiations/phone_interview?resume_id&#x3D;123456&amp;vacancy_id&#x3D;654321&amp;message&#x3D;new_msg &#x60;&#x60;&#x60; 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param resumeId Идентификатор резюме (required)
     * @param vacancyId Идентификатор вакансии (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param message Сообщение, которое будет отправлено соискателю на электронную почту. Используйте [шаблоны](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-mail-templates) для получения текстов (optional)
     * @param sendSms Если установлено &#x60;true&#x60;, соискателю будет отправлено SMS-уведомление о приглашении. Обратите внимание, что в SMS-сообщении используется стандартный текст, изменить его нельзя (optional, default to false)
     * @return Результат приглашения на вакансию (status code 201)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Невозможно пригласить на вакансию (status code 403)
     */
    @Operation(
        operationId = "inviteApplicantToVacancy",
        summary = "Пригласить соискателя на вакансию",
        description = "Запрос формирует приглашение на вакансию для соискателя по инициативе работодателя.  > Вместо `phone_interview` необходимо сформировать запрос из параметра `negotiations_actions[].url` [списка подходящих вакансий к резюме](#tag/Upravlenie-vakansiyami/operation/get-active-vacancy-list), передав аргументы из массива `negotiations_actions[].arguments`.  Пример запроса:  ``` POST /negotiations/phone_interview?resume_id=123456&vacancy_id=654321&message=new_msg ``` ",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Результат приглашения на вакансию", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadRequestBadArgumentBadRequestAndBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Невозможно пригласить на вакансию", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsVacancyApplyForbiddenErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsVacancyApplyForbiddenErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/negotiations/phone_interview",
        produces = { "text/html", "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<String> inviteApplicantToVacancy(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "resume_id", description = "Идентификатор резюме", required = true) @Valid @RequestParam(value = "resume_id", required = true) String resumeId,
        @Parameter(name = "vacancy_id", description = "Идентификатор вакансии", required = true) @Valid @RequestParam(value = "vacancy_id", required = true) String vacancyId,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "message", description = "Сообщение, которое будет отправлено соискателю на электронную почту. Используйте [шаблоны](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-mail-templates) для получения текстов") @Valid @RequestParam(value = "message", required = false) String message,
        @Parameter(name = "send_sms", description = "Если установлено `true`, соискателю будет отправлено SMS-уведомление о приглашении. Обратите внимание, что в SMS-сообщении используется стандартный текст, изменить его нельзя") @Valid @RequestParam(value = "send_sms", required = false) Boolean sendSms
    );


    /**
     * POST /negotiations/read : Отметить отклики прочитанными
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param topicId Идентификаторы откликов (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Текущий пользователь не является работодателем (status code 403)
     *         or Топик не существует или недоступен для текущего пользователя (status code 404)
     */
    @Operation(
        operationId = "postNegotiationsTopicsRead",
        summary = "Отметить отклики прочитанными",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Топик не существует или недоступен для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/negotiations/read",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<Void> postNegotiationsTopicsRead(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "topic_id", description = "Идентификаторы откликов", required = true) @Valid @RequestParam(value = "topic_id", required = true) String topicId,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /negotiations/{id} : Действия по откликам/приглашениям
     * Работодатель может изменять состояние (state) отклика для соискателя, чтобы повысить качество обратной связи и упростить работу со статистикой откликов.  Если работодатель, используя данный метод, отправляет соискателю сообщение об изменении состояния отклика/приглашения (поле &#x60;message&#x60; в теле запроса), это приведет также к изменению соискательского состояния отклика/приглашения.  Обязательность аргументов в теле запроса отличается для разных откликов/приглашений. Проверить, является ли аргумент обязательным можно в поле &#x60;actions.arguments&#x60;, которое возвращается для каждого отклика в [списке откликов/приглашений](https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#действия-по-откликуприглашению-actions) 
     *
     * @param id Идентификатор [коллекции](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) топиков, в которую будет перенесено состояние отклика (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param topicId Идентификаторы откликов. Допускается передавать не более 50 идентификаторов, перечисляя их через амперсанд, например: &#x60;topic_id&#x3D;1&amp;topic_id&#x3D;2&amp;topic_id&#x3D;3...&amp;topic_id&#x3D;50&#x60;  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param addressId Идентификатор [адреса](https://api.hh.ru/openapi/redoc#tag/Adresa-rabotodatelya), который будет указан в приглашении (optional)
     * @param message Сообщение, которое будет отправлено соискателю на электронную почту. Используйте [шаблоны](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-mail-templates) для получения текстов (optional)
     * @param sendSms Если установлено &#x60;true&#x60;, соискателю будет отправлено SMS-уведомление о приглашении. Обратите внимание, что в SMS-сообщении используется стандартный текст, изменить его нельзя (optional, default to false)
     * @return Успешный ответ (status code 204)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Ошибка доступа к отклику/приглашению (status code 403)
     *         or Топик не существует или недоступен для текущего пользователя (status code 404)
     */
    @Operation(
        operationId = "putNegotiationsCollectionToNextState",
        summary = "Действия по откликам/приглашениям",
        description = "Работодатель может изменять состояние (state) отклика для соискателя, чтобы повысить качество обратной связи и упростить работу со статистикой откликов.  Если работодатель, используя данный метод, отправляет соискателю сообщение об изменении состояния отклика/приглашения (поле `message` в теле запроса), это приведет также к изменению соискательского состояния отклика/приглашения.  Обязательность аргументов в теле запроса отличается для разных откликов/приглашений. Проверить, является ли аргумент обязательным можно в поле `actions.arguments`, которое возвращается для каждого отклика в [списке откликов/приглашений](https://github.com/hhru/api/blob/master/docs/employer_negotiations.md#действия-по-откликуприглашению-actions) ",
        tags = { "Отклики/приглашения работодателя", "Отклики/приглашения работодателя на уровне работодателя" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка доступа к отклику/приглашению", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationForbiddenErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Топик не существует или недоступен для текущего пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/negotiations/{id}",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<Void> putNegotiationsCollectionToNextState(
        @Parameter(name = "id", description = "Идентификатор [коллекции](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiations) топиков, в которую будет перенесено состояние отклика", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "topic_id", description = "Идентификаторы откликов. Допускается передавать не более 50 идентификаторов, перечисляя их через амперсанд, например: `topic_id=1&topic_id=2&topic_id=3...&topic_id=50` ", required = true) @Valid @RequestParam(value = "topic_id", required = true) String topicId,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "address_id", description = "Идентификатор [адреса](https://api.hh.ru/openapi/redoc#tag/Adresa-rabotodatelya), который будет указан в приглашении") @Valid @RequestParam(value = "address_id", required = false) String addressId,
        @Parameter(name = "message", description = "Сообщение, которое будет отправлено соискателю на электронную почту. Используйте [шаблоны](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-mail-templates) для получения текстов") @Valid @RequestParam(value = "message", required = false) String message,
        @Parameter(name = "send_sms", description = "Если установлено `true`, соискателю будет отправлено SMS-уведомление о приглашении. Обратите внимание, что в SMS-сообщении используется стандартный текст, изменить его нельзя") @Valid @RequestParam(value = "send_sms", required = false) Boolean sendSms
    );


    /**
     * POST /negotiations/{nid}/messages : Отправка нового сообщения
     * Запрос отправляет новое сообщение в рамках переписки.  Отправить новое сообщение можно, если:  * Работодатель пригласил соискателя на вакансию. * Соискатель оставил отклик на вакансию.  Если вакансия была отправлена в архив или соискатель удалил резюме, переписка будет недоступна. Работодатель также может вручную отключить переписку для вакансии.  ‼️ Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и    [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться.   В связи с этим переписка может некорректно отображаться 
     *
     * @param nid Идентификатор отклика/приглашения (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @param message Сообщение отклика/приглашения (optional)
     * @return Сообщение отправлено. Обратите внимание:  для работодателя возвращаемый &#x60;Content-type: text/html&#x60;, а для соискателя - &#x60;application/json&#x60;  (status code 201)
     *         or Ошибка в параметрах запроса (status code 400)
     *         or Не удалось отправить сообщение (status code 403)
     *         or Указанный отклик/приглашение не найден или у текущего пользователя нет доступа (status code 404)
     */
    @Operation(
        operationId = "sendNegotiationMessage",
        summary = "Отправка нового сообщения",
        description = "Запрос отправляет новое сообщение в рамках переписки.  Отправить новое сообщение можно, если:  * Работодатель пригласил соискателя на вакансию. * Соискатель оставил отклик на вакансию.  Если вакансия была отправлена в архив или соискатель удалил резюме, переписка будет недоступна. Работодатель также может вручную отключить переписку для вакансии.  ‼️ Обратите внимание, что методы для работы с сообщениями в рамках отклика/приглашения от имени [соискателя](#tag/Perepiska-(otklikipriglasheniya)-dlya-soiskatelya/operation/get-negotiation-messages) и    [менеджера работодателя](#tag/Otklikipriglasheniya-rabotodatelya/operation/get-negotiation-messages) устарели, и новые возможности [чатов](https://feedback.hh.ru/knowledge-base/article/1290) в них не будут поддерживаться.   В связи с этим переписка может некорректно отображаться ",
        tags = { "Переписка (отклики/приглашения) для соискателя", "Отклики/приглашения работодателя" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Сообщение отправлено. Обратите внимание:  для работодателя возвращаемый `Content-type: text/html`, а для соискателя - `application/json` ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NegotiationsMessageSent.class)),
                @Content(mediaType = "text/html", schema = @Schema(implementation = NegotiationsMessageSent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметрах запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class)),
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Не удалось отправить сообщение", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationNegotiationsBadAuthorizationErrors.class)),
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsNegotiationNegotiationsBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Указанный отклик/приглашение не найден или у текущего пользователя нет доступа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsNegotiationNegotiationsNotFoundErrors.class)),
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsNegotiationNegotiationsNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/negotiations/{nid}/messages",
        produces = { "application/json", "text/html" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<NegotiationsMessageSent> sendNegotiationMessage(
        @Parameter(name = "nid", description = "Идентификатор отклика/приглашения", required = true, in = ParameterIn.PATH) @PathVariable("nid") String nid,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host,
        @Parameter(name = "message", description = "Сообщение отклика/приглашения") @Valid @RequestParam(value = "message", required = false) String message
    );

}
