/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.brobrocode.cadra.client.config.HhApiFeignConfiguration;
import ru.brobrocode.cadra.client.model.ConfirmPhoneInResume400Response;
import ru.brobrocode.cadra.client.model.ConfirmPhoneInResume403Response;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Резюме. Работа с телефоном", description = "Действия с резюме соискателя связанные с отправкой/получением информации на его телефон")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}", configuration = HhApiFeignConfiguration.class)
public interface ResumePhoneConfirmApi {

    /**
     * POST /resume_phone_confirm : Подтвердить телефон кодом
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param phone Телефон который надо подтвердить (required)
     * @param confirmationCode Код для подтверждения (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ, номер верифицирован (status code 200)
     *         or Ошибки в аргументах (status code 400)
     *         or Ошибка авторизации (status code 403)
     */
    @Operation(
        operationId = "confirmPhoneInResume",
        summary = "Подтвердить телефон кодом",
        tags = { "Резюме. Работа с телефоном" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ, номер верифицирован"),
            @ApiResponse(responseCode = "400", description = "Ошибки в аргументах", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConfirmPhoneInResume400Response.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConfirmPhoneInResume403Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/resume_phone_confirm",
        produces = { "application/json" },
        consumes = { "application/x-www-form-urlencoded" }
    )
    
    ResponseEntity<Void> confirmPhoneInResume(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "phone", description = "Телефон который надо подтвердить", required = true) @Valid @RequestParam(value = "phone", required = true) String phone,
        @Parameter(name = "confirmation_code", description = "Код для подтверждения", required = true) @Valid @RequestParam(value = "confirmation_code", required = true) String confirmationCode,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
