/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.brobrocode.cadra.client.model.*;

import java.math.BigDecimal;

import ru.brobrocode.cadra.client.config.HhApiFeignConfiguration;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Сохраненные поиски резюме", description = "Сохраненный поиск (автопоиск) — это сохраненный набор параметров поиска, по которому можно отслеживать новые резюме по заданному запросу. Помимо сохранения параметров поисковых запросов, автопоиск позволяет получать оповещения о новых результатах поиска. Для удобства автопоиску можно задавать имя")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}", configuration = HhApiFeignConfiguration.class)
public interface SavedSearchesApi {

    /**
     * POST /saved_searches/resumes : Создание нового сохраненного поиска резюме
     * Некоторые параметры принимают множественные значения: &#x60;key&#x3D;value&amp;key&#x3D;value&#x60;.  При указании параметров пагинации (&#x60;page&#x60;, &#x60;per_page&#x60;) работает ограничение: глубина возвращаемых результатов не может быть больше 2000. Например, возможен запрос &#x60;per_page&#x3D;10&amp;page&#x3D;199&#x60; (выдача с 1991 по 2000 вакансию), но запрос с &#x60;per_page&#x3D;10&amp;page&#x3D;200&#x60; вернёт ошибку (выдача с 2001 до 2010 вакансию) 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param text Поисковая фраза. Метод найдет резюме, в которых встречаются все слова заданной фразы.  Особенности:  * Можно указать несколько значений. Каждое дополнительное значение уточняет поиск. * В качестве поисковой фразы можно использовать [язык поисковых запросов](https://hh.ru/article/1175). * Специально для этого поля предусмотрено [автодополнение по подсказкам](#tag/Podskazki/operation/get-resume-search-keywords-suggests). * Для тонкой настройки по фразе можно использовать параметры &#x60;text.logic&#x60;, &#x60;text.field&#x60;, &#x60;text.period&#x60;. При использовании дополнительных &#x60;text.*&#x60; полей, необходимо указывать весь набор (триаду) параметров  (optional)
     * @param textLogic Описывает, как производится поиск. Возможные значения перечислены в поле &#x60;resume_search_logic&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries) (optional)
     * @param textField Описывает, где должны встречаться слова из поисковой фразы &#x60;text&#x60;. Можно указать несколько значений через запятую, например &#x60;?text.field&#x3D;education,keywords&#x60;. Возможные значения перечислены в поле &#x60;resume_search_fields&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries) (optional)
     * @param textPeriod Период опыта работы.  Параметр имеет смысл только при &#x60;text.field&#x60; равным одному из значений: &#x60;experience&#x60;, &#x60;experience_company&#x60;, &#x60;experience_position&#x60;, &#x60;experience_description&#x60;, но указывать его необходимо всегда при указании других &#x60;text.*&#x60;. Если параметр не имеет смысла, то его значение можно оставить пустым  (optional)
     * @param ageFrom Нижняя граница возраста соискателя в годах.  По умолчанию в выдачу добавляются также резюме с неуказанным возрастом. Для выдачи резюме только с указанным возрастом передайте значение &#x60;only_with_age&#x60; в параметре &#x60;label&#x60;  (optional)
     * @param ageTo Верхняя граница возраста соискателя в годах.  По умолчанию в выдачу добавляются также резюме с неуказанным возрастом. Для выдачи резюме только с указанным возрастом передайте значение &#x60;only_with_age&#x60; в параметре &#x60;label&#x60;  (optional)
     * @param area Регион. Возможные значения указаны в [справочнике регионов](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений.  По умолчанию выбираются резюме, в которых соискатели живут в указанных регионах или готовы в них переехать. Поменять это поведение поиска можно, указав параметр &#x60;relocation&#x60;  (optional)
     * @param relocation Готовность к переезду. Возможные значения указаны в поле &#x60;resume_search_relocation&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Необходимо указывать вместе с параметром &#x60;area&#x60;  (optional)
     * @param period Поиск ведется по резюме, опубликованным за указанный период в днях. Если период не указан, поиск ведется без ограничений по дате публикации  (optional)
     * @param dateFrom Дата, от которой нужно начать поиск. Значение указывается в формате [ISO 8601](#date-format) — &#x60;YYYY-MM-DD&#x60; или с точностью до секунды &#x60;YYYY-MM-DDThh:mm:ss±hhmm&#x60;. Нельзя передавать вместе с параметром &#x60;period&#x60;  (optional)
     * @param dateTo Дата, до которой нужно искать. Значение указывается в формате [ISO 8601](#date-format) — &#x60;YYYY-MM-DD&#x60; или с точность до секунды &#x60;YYYY-MM-DDThh:mm:ss±hhmm&#x60;. Можно передавать только в паре с параметром &#x60;date_from&#x60;. Нельзя передавать вместе с параметром &#x60;period&#x60;  (optional)
     * @param educationLevel Уровень образования. Возможные значения перечислены в поле &#x60;education_level&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Если параметр не указан, поиск ведется без ограничений на уровень образования  (optional)
     * @param employment Тип занятости. Возможные значения перечислены в поле &#x60;employment&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param experience Опыт работы. Возможные значения перечислены в поле &#x60;experience&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param skill Ключевые навыки. Указывается один или несколько идентификаторов ключевых навыков. Значения можно получить из поля &#x60;id&#x60; в [подсказке по ключевым навыкам](#tag/Podskazki/operation/get-skill-set-suggests)  (optional)
     * @param gender Пол соискателя. Возможные значения перечислены в поле &#x60;gender&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries).  По умолчанию вне зависимости от значения параметра будут найдены резюме, в которых пол не указан, убрать такие резюме можно с помощью параметра &#x60;label&#x3D;only_with_gender&#x60;  (optional)
     * @param label Дополнительный фильтр. Возможные значения перечислены в поле &#x60;resume_search_label&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param language Знание языка. Можно указать несколько значений. Задается в формате &#x60;language.level&#x60;, где:  * &#x60;language&#x60; — значение из [справочника языков](#tag/Obshie-spravochniki/operation/get-languages); * &#x60;level&#x60; — значение поля language_level из [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  Например, &#x60;ita.c2&#x60;  (optional)
     * @param metro Линия, либо станция метро. Возможные значения перечислены в [справочнике метро](#tag/Obshie-spravochniki/operation/get-metro-stations)  (optional)
     * @param currency Код валюты. Возможные значения перечислены в поле &#x60;currency.code&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  (optional)
     * @param salaryFrom Нижняя граница желаемой заработной платы (ЗП).  По умолчанию в выдачу добавляются также резюме с неуказанной ЗП. Для выдачи резюме только с указанной ЗП передайте параметр &#x60;label&#x3D;only_with_salary&#x60;  (optional)
     * @param salaryTo Верхняя граница желаемой заработной платы (ЗП).  По умолчанию в выдачу добавляются также резюме с неуказанной ЗП. Для выдачи резюме только с указанной ЗП передайте параметр &#x60;label&#x3D;only_with_salary&#x60;  (optional)
     * @param schedule График работы. Возможные значения перечислены в поле &#x60;schedule&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param orderBy Сортировка списка резюме. Возможные значения перечислены в поле &#x60;resume_search_order&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  (optional)
     * @param citizenship Страна гражданства соискателя. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений  (optional)
     * @param workTicket Страна, в которой у соискателя есть разрешение на работу. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений  (optional)
     * @param educationalInstitution Учебные заведения соискателя. В качестве параметров используются [подсказки по названиям университетов](#tag/Podskazki). Можно указать несколько значений  (optional)
     * @param searchInResponses Если &#x60;true&#x60;, то поиск осуществляется только по резюме, которыми соискатели откликались на вакансии компании текущего пользователя, если &#x60;false&#x60; — поиск осуществляется по всем резюме. По умолчанию — &#x60;false&#x60;  (optional)
     * @param byTextPrefix Если &#x60;true&#x60;, включается поиск по префиксу. Для каждого параметра &#x60;text&#x60; будут находиться не только полные совпадения слов, но еще и слова, начинающиеся с &#x60;text&#x60;. По умолчанию — &#x60;false&#x60;  (optional)
     * @param driverLicenseTypes Категории водительских прав соискателя. Возможные значения перечислены в поле &#x60;driver_license_types&#x60; в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param vacancyId Идентификатор вакансии для поиска похожих резюме. Необходимо передавать идентификатор активной вакансии работодателя или вакансии работодателя в архиве  (optional)
     * @param page Номер страницы (считается от 0, по умолчанию — 0) (optional)
     * @param perPage Количество элементов (по умолчанию — 10, максимальное значение — 50) (optional)
     * @param professionalRole Профессиональная роль. Элемент справочника [профессиональных ролей](#tag/Obshie-spravochniki/operation/get-professional-roles-dictionary). Можно указать несколько значений  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешно создано (status code 201)
     *         or Ошибки в аргументах (status code 400)
     *         or Текущий пользователь не является работодателем (status code 403)
     */
    @Operation(
        operationId = "createSavedResumeSearch",
        summary = "Создание нового сохраненного поиска резюме",
        description = "Некоторые параметры принимают множественные значения: `key=value&key=value`.  При указании параметров пагинации (`page`, `per_page`) работает ограничение: глубина возвращаемых результатов не может быть больше 2000. Например, возможен запрос `per_page=10&page=199` (выдача с 1991 по 2000 вакансию), но запрос с `per_page=10&page=200` вернёт ошибку (выдача с 2001 до 2010 вакансию) ",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Успешно создано", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки в аргументах", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/saved_searches/resumes",
        produces = { "text/html", "application/json" }
    )
    
    ResponseEntity<String> createSavedResumeSearch(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "text", description = "Поисковая фраза. Метод найдет резюме, в которых встречаются все слова заданной фразы.  Особенности:  * Можно указать несколько значений. Каждое дополнительное значение уточняет поиск. * В качестве поисковой фразы можно использовать [язык поисковых запросов](https://hh.ru/article/1175). * Специально для этого поля предусмотрено [автодополнение по подсказкам](#tag/Podskazki/operation/get-resume-search-keywords-suggests). * Для тонкой настройки по фразе можно использовать параметры `text.logic`, `text.field`, `text.period`. При использовании дополнительных `text.*` полей, необходимо указывать весь набор (триаду) параметров ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = false) String text,
        @Parameter(name = "text.logic", description = "Описывает, как производится поиск. Возможные значения перечислены в поле `resume_search_logic` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "text.logic", required = false) String textLogic,
        @Parameter(name = "text.field", description = "Описывает, где должны встречаться слова из поисковой фразы `text`. Можно указать несколько значений через запятую, например `?text.field=education,keywords`. Возможные значения перечислены в поле `resume_search_fields` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "text.field", required = false) String textField,
        @Parameter(name = "text.period", description = "Период опыта работы.  Параметр имеет смысл только при `text.field` равным одному из значений: `experience`, `experience_company`, `experience_position`, `experience_description`, но указывать его необходимо всегда при указании других `text.*`. Если параметр не имеет смысла, то его значение можно оставить пустым ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "text.period", required = false) String textPeriod,
        @Parameter(name = "age_from", description = "Нижняя граница возраста соискателя в годах.  По умолчанию в выдачу добавляются также резюме с неуказанным возрастом. Для выдачи резюме только с указанным возрастом передайте значение `only_with_age` в параметре `label` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "age_from", required = false) BigDecimal ageFrom,
        @Parameter(name = "age_to", description = "Верхняя граница возраста соискателя в годах.  По умолчанию в выдачу добавляются также резюме с неуказанным возрастом. Для выдачи резюме только с указанным возрастом передайте значение `only_with_age` в параметре `label` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "age_to", required = false) BigDecimal ageTo,
        @Parameter(name = "area", description = "Регион. Возможные значения указаны в [справочнике регионов](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений.  По умолчанию выбираются резюме, в которых соискатели живут в указанных регионах или готовы в них переехать. Поменять это поведение поиска можно, указав параметр `relocation` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "area", required = false) String area,
        @Parameter(name = "relocation", description = "Готовность к переезду. Возможные значения указаны в поле `resume_search_relocation` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Необходимо указывать вместе с параметром `area` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "relocation", required = false) String relocation,
        @Parameter(name = "period", description = "Поиск ведется по резюме, опубликованным за указанный период в днях. Если период не указан, поиск ведется без ограничений по дате публикации ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "period", required = false) BigDecimal period,
        @Parameter(name = "date_from", description = "Дата, от которой нужно начать поиск. Значение указывается в формате [ISO 8601](#date-format) — `YYYY-MM-DD` или с точностью до секунды `YYYY-MM-DDThh:mm:ss±hhmm`. Нельзя передавать вместе с параметром `period` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_from", required = false) String dateFrom,
        @Parameter(name = "date_to", description = "Дата, до которой нужно искать. Значение указывается в формате [ISO 8601](#date-format) — `YYYY-MM-DD` или с точность до секунды `YYYY-MM-DDThh:mm:ss±hhmm`. Можно передавать только в паре с параметром `date_from`. Нельзя передавать вместе с параметром `period` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_to", required = false) String dateTo,
        @Parameter(name = "education_level", description = "Уровень образования. Возможные значения перечислены в поле `education_level` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Если параметр не указан, поиск ведется без ограничений на уровень образования ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "education_level", required = false) String educationLevel,
        @Parameter(name = "employment", description = "Тип занятости. Возможные значения перечислены в поле `employment` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "employment", required = false) String employment,
        @Parameter(name = "experience", description = "Опыт работы. Возможные значения перечислены в поле `experience` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "experience", required = false) String experience,
        @Parameter(name = "skill", description = "Ключевые навыки. Указывается один или несколько идентификаторов ключевых навыков. Значения можно получить из поля `id` в [подсказке по ключевым навыкам](#tag/Podskazki/operation/get-skill-set-suggests) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "skill", required = false) String skill,
        @Parameter(name = "gender", description = "Пол соискателя. Возможные значения перечислены в поле `gender` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries).  По умолчанию вне зависимости от значения параметра будут найдены резюме, в которых пол не указан, убрать такие резюме можно с помощью параметра `label=only_with_gender` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "gender", required = false) String gender,
        @Parameter(name = "label", description = "Дополнительный фильтр. Возможные значения перечислены в поле `resume_search_label` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "label", required = false) String label,
        @Parameter(name = "language", description = "Знание языка. Можно указать несколько значений. Задается в формате `language.level`, где:  * `language` — значение из [справочника языков](#tag/Obshie-spravochniki/operation/get-languages); * `level` — значение поля language_level из [справочника полей](#tag/Obshie-spravochniki/operation/get-dictionaries)  Например, `ita.c2` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "language", required = false) String language,
        @Parameter(name = "metro", description = "Линия, либо станция метро. Возможные значения перечислены в [справочнике метро](#tag/Obshie-spravochniki/operation/get-metro-stations) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "metro", required = false) String metro,
        @Parameter(name = "currency", description = "Код валюты. Возможные значения перечислены в поле `currency.code` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "currency", required = false) String currency,
        @Parameter(name = "salary_from", description = "Нижняя граница желаемой заработной платы (ЗП).  По умолчанию в выдачу добавляются также резюме с неуказанной ЗП. Для выдачи резюме только с указанной ЗП передайте параметр `label=only_with_salary` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "salary_from", required = false) BigDecimal salaryFrom,
        @Parameter(name = "salary_to", description = "Верхняя граница желаемой заработной платы (ЗП).  По умолчанию в выдачу добавляются также резюме с неуказанной ЗП. Для выдачи резюме только с указанной ЗП передайте параметр `label=only_with_salary` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "salary_to", required = false) BigDecimal salaryTo,
        @Parameter(name = "schedule", description = "График работы. Возможные значения перечислены в поле `schedule` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "schedule", required = false) String schedule,
        @Parameter(name = "order_by", description = "Сортировка списка резюме. Возможные значения перечислены в поле `resume_search_order` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "citizenship", description = "Страна гражданства соискателя. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "citizenship", required = false) String citizenship,
        @Parameter(name = "work_ticket", description = "Страна, в которой у соискателя есть разрешение на работу. Возможные значения перечислены в [справочнике стран](#tag/Obshie-spravochniki/operation/get-countries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "work_ticket", required = false) String workTicket,
        @Parameter(name = "educational_institution", description = "Учебные заведения соискателя. В качестве параметров используются [подсказки по названиям университетов](#tag/Podskazki). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "educational_institution", required = false) String educationalInstitution,
        @Parameter(name = "search_in_responses", description = "Если `true`, то поиск осуществляется только по резюме, которыми соискатели откликались на вакансии компании текущего пользователя, если `false` — поиск осуществляется по всем резюме. По умолчанию — `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search_in_responses", required = false) Boolean searchInResponses,
        @Parameter(name = "by_text_prefix", description = "Если `true`, включается поиск по префиксу. Для каждого параметра `text` будут находиться не только полные совпадения слов, но еще и слова, начинающиеся с `text`. По умолчанию — `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "by_text_prefix", required = false) Boolean byTextPrefix,
        @Parameter(name = "driver_license_types", description = "Категории водительских прав соискателя. Возможные значения перечислены в поле `driver_license_types` в [справочнике полей](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "driver_license_types", required = false) String driverLicenseTypes,
        @Parameter(name = "vacancy_id", description = "Идентификатор вакансии для поиска похожих резюме. Необходимо передавать идентификатор активной вакансии работодателя или вакансии работодателя в архиве ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "vacancy_id", required = false) String vacancyId,
        @Parameter(name = "page", description = "Номер страницы (считается от 0, по умолчанию — 0)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @Parameter(name = "per_page", description = "Количество элементов (по умолчанию — 10, максимальное значение — 50)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false) BigDecimal perPage,
        @Parameter(name = "professional_role", description = "Профессиональная роль. Элемент справочника [профессиональных ролей](#tag/Obshie-spravochniki/operation/get-professional-roles-dictionary). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "professional_role", required = false) String professionalRole,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * POST /saved_searches/vacancies : Создание нового сохраненного поиска вакансий
     * Некоторые параметры принимают множественные значения: &#x60;key&#x3D;value&amp;key&#x3D;value&#x60;.  При указании параметров пагинации (&#x60;page&#x60;, &#x60;per_page&#x60;) работает ограничение: глубина возвращаемых результатов не может быть больше 2000. Например, возможен запрос &#x60;per_page&#x3D;10&amp;page&#x3D;199&#x60; (выдача с 1991 по 2000 вакансию), но запрос с &#x60;per_page&#x3D;10&amp;page&#x3D;200&#x60; вернёт ошибку (выдача с 2001 до 2010 вакансию) 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (считается от 0, по умолчанию - 0) (optional)
     * @param perPage Количество элементов (по умолчанию - 10, максимальное значение - 100) (optional)
     * @param text Переданное значение ищется в полях вакансии, указанных в параметре &#x60;search_field&#x60;. Доступен [язык запросов](https://hh.ru/article/1175). Специально для этого поля есть [автодополнение](#tag/Podskazki/operation/get-vacancy-search-keywords) (optional)
     * @param name Название нового автопоиска (optional)
     * @param searchField Область поиска. Справочник с возможными значениями: &#x60;vacancy_search_fields&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). По умолчанию, используются все поля. Можно указать несколько значений  (optional)
     * @param experience Опыт работы. Необходимо передавать &#x60;id&#x60; из справочника &#x60;experience&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param employment Тип занятости. Необходимо передавать &#x60;id&#x60; из справочника &#x60;employment&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param schedule График работы. Необходимо передавать &#x60;id&#x60; из справочника &#x60;schedule&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param area Регион. Необходимо передавать &#x60;id&#x60; из справочника [/areas](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений  (optional)
     * @param metro Ветка или станция метро. Необходимо передавать &#x60;id&#x60; из справочника [/metro](#tag/Obshie-spravochniki/operation/get-metro-stations). Можно указать несколько значений  (optional)
     * @param professionalRole Профессиональная область. Необходимо передавать &#x60;id&#x60; из справочника [/professional_roles](#tag/Obshie-spravochniki/operation/get-professional-roles-dictionary)  (optional)
     * @param industry Индустрия компании, разместившей вакансию. Необходимо передавать &#x60;id&#x60; из справочника [/industries](#tag/Obshie-spravochniki/operation/get-industries). Можно указать несколько значений  (optional)
     * @param employerId Идентификатор [работодателя](#tag/Rabotodatel). Можно указать несколько значений  (optional)
     * @param currency Код валюты. Справочник с возможными значениями: &#x60;currency&#x60; (ключ &#x60;code&#x60;) в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Имеет смысл указывать только совместно с параметром &#x60;salary&#x60;  (optional)
     * @param salary Размер заработной платы. Если указано это поле, но не указано &#x60;currency&#x60;, то для &#x60;currency&#x60; используется значение RUR.  При указании значения будут найдены вакансии, в которых вилка зарплаты близка к указанной в запросе. При этом значения пересчитываются по текущим курсам ЦБ РФ. Например, при указании &#x60;salary&#x3D;100&amp;currency&#x3D;EUR&#x60; будут найдены вакансии, где вилка зарплаты указана в рублях и после пересчёта в Евро близка к 100 EUR.  По умолчанию будут также найдены вакансии, в которых вилка зарплаты не указана, чтобы такие вакансии отфильтровать, используйте &#x60;only_with_salary&#x3D;true&#x60;  (optional)
     * @param label Фильтр по меткам вакансий. Необходимо передавать &#x60;id&#x60; из справочника &#x60;vacancy_label&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений  (optional)
     * @param onlyWithSalary Показывать вакансии только с указанием зарплаты. По умолчанию &#x60;false&#x60;  (optional)
     * @param period Количество дней, в пределах которых производится поиск по вакансиям  (optional)
     * @param dateFrom Дата, которая ограничивает снизу диапазон дат публикации вакансий. Нельзя передавать вместе с параметром &#x60;period&#x60;.  Значение указывается в формате &#x60;ISO 8601 - YYYY-MM-DD&#x60; или с точность до секунды &#x60;YYYY-MM-DDThh:mm:ss±hhmm&#x60;. Указанное значение будет округлено до ближайших пяти минут  (optional)
     * @param dateTo Дата, которая ограничивает сверху диапазон дат публикации вакансий. Нельзя передавать вместе с параметром &#x60;period&#x60;.  Значение указывается в формате &#x60;ISO 8601 - YYYY-MM-DD&#x60; или с точность до секунды &#x60;YYYY-MM-DDThh:mm:ss±hhmm&#x60;. Указанное значение будет округлено до ближайших пяти минут  (optional)
     * @param topLat Верхняя граница широты.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка  (optional)
     * @param bottomLat Нижняя граница широты.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка  (optional)
     * @param leftLng Левая граница долготы.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка  (optional)
     * @param rightLng Правая граница долготы.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка  (optional)
     * @param orderBy Сортировка списка вакансий. Справочник с возможными значениями: &#x60;vacancy_search_order&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries).  Если выбрана сортировка по удалённости от гео-точки &#x60;distance&#x60;, необходимо также задать её координаты: &#x60;sort_point_lat&#x60;, &#x60;sort_point_lng&#x60;  (optional)
     * @param sortPointLat Значение географической широты точки, по расстоянию от которой будут отсортированы вакансии. Необходимо указывать только, если &#x60;order_by&#x60; установлено в &#x60;distance&#x60;  (optional)
     * @param sortPointLng Значение географической долготы точки, по расстоянию от которой будут отсортированы вакансии. Необходимо указывать только, если &#x60;order_by&#x60; установлено в &#x60;distance&#x60;  (optional)
     * @param clusters Возвращать ли [кластеры для данного поиска](#tag/Poisk-vakansij/Klastery-v-poiske-vakansij). По умолчанию — &#x60;false&#x60;  (optional)
     * @param describeArguments Возвращать ли описание использованных параметров поиска. Успешный ответ будет содержать поле [&#x60;arguments&#x60;]((#tag/Poisk-vakansij/operation/get-vacancies))).  По умолчанию — &#x60;false&#x60;  (optional)
     * @param noMagic Если значение &#x60;true&#x60; — автоматическое преобразование вакансий отключено. По умолчанию – false.  При включённом автоматическом преобразовании, будет предпринята попытка изменить текстовый запрос пользователя на набор параметров. Например, запрос &#x60;text&#x3D;москва бухгалтер 100500&#x60; будет преобразован в &#x60;text&#x3D;бухгалтер&amp;only_with_salary&#x3D;true&amp;area&#x3D;1&amp;salary&#x3D;100500&#x60;  (optional)
     * @param premium Если значение &#x60;true&#x60; — в сортировке вакансий будет учтены премиум вакансии. Такая сортировка используется на сайте. По умолчанию — false  (optional)
     * @param responsesCountEnabled Если значение &#x60;true&#x60; — дополнительное поле &#x60;counters&#x60; с количеством откликов для вакансии включено. По-умолчанию — &#x60;false&#x60;  (optional)
     * @param partTime Вакансии для подработки. Возможные значения:  * Все элементы из &#x60;working_days&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Все элементы из &#x60;working_time_intervals&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Все элементы из &#x60;working_time_modes&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Элементы &#x60;part&#x60; или &#x60;project&#x60; из &#x60;employment&#x60; в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Элемент &#x60;accept_temporary&#x60;, показывает вакансии только с временным трудоустройством.  Можно указать несколько значений  (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешно создано (status code 201)
     *         or Ошибки в аргументах (status code 400)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "createSavedVacancySearch",
        summary = "Создание нового сохраненного поиска вакансий",
        description = "Некоторые параметры принимают множественные значения: `key=value&key=value`.  При указании параметров пагинации (`page`, `per_page`) работает ограничение: глубина возвращаемых результатов не может быть больше 2000. Например, возможен запрос `per_page=10&page=199` (выдача с 1991 по 2000 вакансию), но запрос с `per_page=10&page=200` вернёт ошибку (выдача с 2001 до 2010 вакансию) ",
        tags = { "Сохраненные поиски вакансий" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Успешно создано", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки в аргументах", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/saved_searches/vacancies",
        produces = { "text/html", "application/json" }
    )
    
    ResponseEntity<String> createSavedVacancySearch(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы (считается от 0, по умолчанию - 0)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @Parameter(name = "per_page", description = "Количество элементов (по умолчанию - 10, максимальное значение - 100)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false) BigDecimal perPage,
        @Parameter(name = "text", description = "Переданное значение ищется в полях вакансии, указанных в параметре `search_field`. Доступен [язык запросов](https://hh.ru/article/1175). Специально для этого поля есть [автодополнение](#tag/Podskazki/operation/get-vacancy-search-keywords)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = false) String text,
        @Parameter(name = "name", description = "Название нового автопоиска", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name,
        @Parameter(name = "search_field", description = "Область поиска. Справочник с возможными значениями: `vacancy_search_fields` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). По умолчанию, используются все поля. Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search_field", required = false) String searchField,
        @Parameter(name = "experience", description = "Опыт работы. Необходимо передавать `id` из справочника `experience` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "experience", required = false) String experience,
        @Parameter(name = "employment", description = "Тип занятости. Необходимо передавать `id` из справочника `employment` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "employment", required = false) String employment,
        @Parameter(name = "schedule", description = "График работы. Необходимо передавать `id` из справочника `schedule` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "schedule", required = false) String schedule,
        @Parameter(name = "area", description = "Регион. Необходимо передавать `id` из справочника [/areas](#tag/Obshie-spravochniki/operation/get-areas). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "area", required = false) String area,
        @Parameter(name = "metro", description = "Ветка или станция метро. Необходимо передавать `id` из справочника [/metro](#tag/Obshie-spravochniki/operation/get-metro-stations). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "metro", required = false) String metro,
        @Parameter(name = "professional_role", description = "Профессиональная область. Необходимо передавать `id` из справочника [/professional_roles](#tag/Obshie-spravochniki/operation/get-professional-roles-dictionary) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "professional_role", required = false) String professionalRole,
        @Parameter(name = "industry", description = "Индустрия компании, разместившей вакансию. Необходимо передавать `id` из справочника [/industries](#tag/Obshie-spravochniki/operation/get-industries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "industry", required = false) String industry,
        @Parameter(name = "employer_id", description = "Идентификатор [работодателя](#tag/Rabotodatel). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "employer_id", required = false) String employerId,
        @Parameter(name = "currency", description = "Код валюты. Справочник с возможными значениями: `currency` (ключ `code`) в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Имеет смысл указывать только совместно с параметром `salary` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "currency", required = false) String currency,
        @Parameter(name = "salary", description = "Размер заработной платы. Если указано это поле, но не указано `currency`, то для `currency` используется значение RUR.  При указании значения будут найдены вакансии, в которых вилка зарплаты близка к указанной в запросе. При этом значения пересчитываются по текущим курсам ЦБ РФ. Например, при указании `salary=100&currency=EUR` будут найдены вакансии, где вилка зарплаты указана в рублях и после пересчёта в Евро близка к 100 EUR.  По умолчанию будут также найдены вакансии, в которых вилка зарплаты не указана, чтобы такие вакансии отфильтровать, используйте `only_with_salary=true` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "salary", required = false) BigDecimal salary,
        @Parameter(name = "label", description = "Фильтр по меткам вакансий. Необходимо передавать `id` из справочника `vacancy_label` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "label", required = false) String label,
        @Parameter(name = "only_with_salary", description = "Показывать вакансии только с указанием зарплаты. По умолчанию `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "only_with_salary", required = false) Boolean onlyWithSalary,
        @Parameter(name = "period", description = "Количество дней, в пределах которых производится поиск по вакансиям ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "period", required = false) BigDecimal period,
        @Parameter(name = "date_from", description = "Дата, которая ограничивает снизу диапазон дат публикации вакансий. Нельзя передавать вместе с параметром `period`.  Значение указывается в формате `ISO 8601 - YYYY-MM-DD` или с точность до секунды `YYYY-MM-DDThh:mm:ss±hhmm`. Указанное значение будет округлено до ближайших пяти минут ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_from", required = false) String dateFrom,
        @Parameter(name = "date_to", description = "Дата, которая ограничивает сверху диапазон дат публикации вакансий. Нельзя передавать вместе с параметром `period`.  Значение указывается в формате `ISO 8601 - YYYY-MM-DD` или с точность до секунды `YYYY-MM-DDThh:mm:ss±hhmm`. Указанное значение будет округлено до ближайших пяти минут ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "date_to", required = false) String dateTo,
        @Parameter(name = "top_lat", description = "Верхняя граница широты.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "top_lat", required = false) BigDecimal topLat,
        @Parameter(name = "bottom_lat", description = "Нижняя граница широты.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "bottom_lat", required = false) BigDecimal bottomLat,
        @Parameter(name = "left_lng", description = "Левая граница долготы.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "left_lng", required = false) BigDecimal leftLng,
        @Parameter(name = "right_lng", description = "Правая граница долготы.  При поиске используется значение указанного в вакансии адреса. Принимаемое значение — градусы в виде десятичной дроби.  Необходимо передавать одновременно все четыре параметра гео-координат, иначе вернется ошибка ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "right_lng", required = false) BigDecimal rightLng,
        @Parameter(name = "order_by", description = "Сортировка списка вакансий. Справочник с возможными значениями: `vacancy_search_order` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries).  Если выбрана сортировка по удалённости от гео-точки `distance`, необходимо также задать её координаты: `sort_point_lat`, `sort_point_lng` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "order_by", required = false) String orderBy,
        @Parameter(name = "sort_point_lat", description = "Значение географической широты точки, по расстоянию от которой будут отсортированы вакансии. Необходимо указывать только, если `order_by` установлено в `distance` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort_point_lat", required = false) BigDecimal sortPointLat,
        @Parameter(name = "sort_point_lng", description = "Значение географической долготы точки, по расстоянию от которой будут отсортированы вакансии. Необходимо указывать только, если `order_by` установлено в `distance` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort_point_lng", required = false) BigDecimal sortPointLng,
        @Parameter(name = "clusters", description = "Возвращать ли [кластеры для данного поиска](#tag/Poisk-vakansij/Klastery-v-poiske-vakansij). По умолчанию — `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "clusters", required = false) Boolean clusters,
        @Parameter(name = "describe_arguments", description = "Возвращать ли описание использованных параметров поиска. Успешный ответ будет содержать поле [`arguments`]((#tag/Poisk-vakansij/operation/get-vacancies))).  По умолчанию — `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "describe_arguments", required = false) Boolean describeArguments,
        @Parameter(name = "no_magic", description = "Если значение `true` — автоматическое преобразование вакансий отключено. По умолчанию – false.  При включённом автоматическом преобразовании, будет предпринята попытка изменить текстовый запрос пользователя на набор параметров. Например, запрос `text=москва бухгалтер 100500` будет преобразован в `text=бухгалтер&only_with_salary=true&area=1&salary=100500` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "no_magic", required = false) Boolean noMagic,
        @Parameter(name = "premium", description = "Если значение `true` — в сортировке вакансий будет учтены премиум вакансии. Такая сортировка используется на сайте. По умолчанию — false ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "premium", required = false) Boolean premium,
        @Parameter(name = "responses_count_enabled", description = "Если значение `true` — дополнительное поле `counters` с количеством откликов для вакансии включено. По-умолчанию — `false` ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "responses_count_enabled", required = false) Boolean responsesCountEnabled,
        @Parameter(name = "part_time", description = "Вакансии для подработки. Возможные значения:  * Все элементы из `working_days` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Все элементы из `working_time_intervals` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Все элементы из `working_time_modes` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Элементы `part` или `project` из `employment` в [/dictionaries](#tag/Obshie-spravochniki/operation/get-dictionaries). * Элемент `accept_temporary`, показывает вакансии только с временным трудоустройством.  Можно указать несколько значений ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "part_time", required = false) Boolean partTime,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * DELETE /saved_searches/resumes/{id} : Удаление сохраненного поиска резюме
     *
     * @param id Идентификатор сохраненного поиска (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка авторизации пользователя (status code 403)
     *         or Не найдено или не доступно текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "deleteSavedResumeSearch",
        summary = "Удаление сохраненного поиска резюме",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Не найдено или не доступно текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/saved_searches/resumes/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteSavedResumeSearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * DELETE /saved_searches/vacancies/{id} : Удаление сохраненного поиска вакансий
     *
     * @param id Идентификатор сохраненного поиска (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка авторизации пользователя (status code 403)
     *         or Не найдено или не доступно текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "deleteSavedVacancySearch",
        summary = "Удаление сохраненного поиска вакансий",
        tags = { "Сохраненные поиски вакансий" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Не найдено или не доступно текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/saved_searches/vacancies/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteSavedVacancySearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /saved_searches/resumes/{id} : Получение единичного сохраненного поиска резюме
     * Внимание: счетчик &#x60;new_items.count&#x60; обновляется раз в час. Из-за этого реальное количество новых найденных резюме  может расходиться со значением этого счетчика 
     *
     * @param id Идентификатор сохраненного поиска из [списка](#tag/Sohranennye-poiski-rezyume/operation/get-saved-resume-searches) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является работодателем (status code 403)
     *         or Сохраненный поиск не найден (status code 404)
     */
    @Operation(
        operationId = "getSavedResumeSearch",
        summary = "Получение единичного сохраненного поиска резюме",
        description = "Внимание: счетчик `new_items.count` обновляется раз в час. Из-за этого реальное количество новых найденных резюме  может расходиться со значением этого счетчика ",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SavedSearchesSavedSearchItem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Сохраненный поиск не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/saved_searches/resumes/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<SavedSearchesSavedSearchItem> getSavedResumeSearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска из [списка](#tag/Sohranennye-poiski-rezyume/operation/get-saved-resume-searches)", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /saved_searches/resumes : Список сохраненных поисков резюме
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (считается от 0, по умолчанию - 0) (optional)
     * @param perPage Количество элементов (по умолчанию - 5, максимальное значение - 10) (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является работодателем (status code 403)
     */
    @Operation(
        operationId = "getSavedResumeSearches",
        summary = "Список сохраненных поисков резюме",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SavedSearchesSavedSearchResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/saved_searches/resumes",
        produces = { "application/json" }
    )
    
    ResponseEntity<SavedSearchesSavedSearchResponse> getSavedResumeSearches(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы (считается от 0, по умолчанию - 0)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @Parameter(name = "per_page", description = "Количество элементов (по умолчанию - 5, максимальное значение - 10)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false) BigDecimal perPage,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /saved_searches/vacancies/{id} : Получение единичного сохраненного поиска вакансий
     *
     * @param id Идентификатор сохраненного поиска (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     *         or Сохраненный поиск не найден (status code 404)
     */
    @Operation(
        operationId = "getSavedVacancySearch",
        summary = "Получение единичного сохраненного поиска вакансий",
        tags = { "Сохраненные поиски вакансий" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SavedSearchesSavedSearchItem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Сохраненный поиск не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/saved_searches/vacancies/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<SavedSearchesSavedSearchItem> getSavedVacancySearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /saved_searches/vacancies : Список сохраненных поисков вакансий
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param page Номер страницы (считается от 0, по умолчанию - 0) (optional)
     * @param perPage Количество элементов (по умолчанию - 10, максимальное значение - 10) (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Текущий пользователь не является соискателем (status code 403)
     */
    @Operation(
        operationId = "getSavedVacancySearches",
        summary = "Список сохраненных поисков вакансий",
        tags = { "Сохраненные поиски вакансий" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SavedSearchesSavedSearchResponse.class))
            }),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является соискателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/saved_searches/vacancies",
        produces = { "application/json" }
    )
    
    ResponseEntity<SavedSearchesSavedSearchResponse> getSavedVacancySearches(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "page", description = "Номер страницы (считается от 0, по умолчанию - 0)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) BigDecimal page,
        @Parameter(name = "per_page", description = "Количество элементов (по умолчанию - 10, максимальное значение - 10)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "per_page", required = false) BigDecimal perPage,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /saved_searches/resumes/{saved_search_id}/managers/{manager_id} : Передача сохраненного поиска резюме другому менеджеру
     *
     * @param savedSearchId Идентификатор из [списка сохраненных поисков](#tag/Sohranennye-poiski-rezyume/operation/get-saved-resume-searches) (required)
     * @param managerId Идентификатор менеджера, которому надо передать автопоиск ([список менеджеров компании](#tag/Menedzhery-rabotodatelya/operation/get-employer-managers)) (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Текущий пользователь не является работодателем (status code 403)
     *         or Автопоиск или менеджер не найден (status code 404)
     */
    @Operation(
        operationId = "moveSavedResumeSearch",
        summary = "Передача сохраненного поиска резюме другому менеджеру",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Текущий пользователь не является работодателем", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsSavedSearchForbiddenErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Автопоиск или менеджер не найден", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsSavedSearchNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/saved_searches/resumes/{saved_search_id}/managers/{manager_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> moveSavedResumeSearch(
        @Parameter(name = "saved_search_id", description = "Идентификатор из [списка сохраненных поисков](#tag/Sohranennye-poiski-rezyume/operation/get-saved-resume-searches)", required = true, in = ParameterIn.PATH) @PathVariable("saved_search_id") String savedSearchId,
        @Parameter(name = "manager_id", description = "Идентификатор менеджера, которому надо передать автопоиск ([список менеджеров компании](#tag/Menedzhery-rabotodatelya/operation/get-employer-managers))", required = true, in = ParameterIn.PATH) @PathVariable("manager_id") String managerId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /saved_searches/resumes/{id} : Обновление сохраненного поиска резюме
     * У сохраненного поиска можно изменить имя (&#x60;name&#x60;) и статус подписки (&#x60;subscription&#x60;). В одном запросе можно передать только один из параметров
     *
     * @param id Идентификатор сохраненного поиска (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param name Новое имя сохраненного поиска (optional)
     * @param subscription Статус подписки (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка в параметре запроса (status code 400)
     *         or Ошибка авторизации пользователя (status code 403)
     *         or Не найдено или не доступно текущему пользователю (status code 404)
     *         or Ошибка запроса при одновременном изменении параметров (status code 409)
     */
    @Operation(
        operationId = "updateSavedResumeSearch",
        summary = "Обновление сохраненного поиска резюме",
        description = "У сохраненного поиска можно изменить имя (`name`) и статус подписки (`subscription`). В одном запросе можно передать только один из параметров",
        tags = { "Сохраненные поиски резюме" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметре запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Не найдено или не доступно текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            }),
            @ApiResponse(responseCode = "409", description = "Ошибка запроса при одновременном изменении параметров", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonConflictBothChangedErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/saved_searches/resumes/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> updateSavedResumeSearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "name", description = "Новое имя сохраненного поиска", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name,
        @Parameter(name = "subscription", description = "Статус подписки", in = ParameterIn.QUERY) @Valid @RequestParam(value = "subscription", required = false) Boolean subscription,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /saved_searches/vacancies/{id} : Обновление сохраненного поиска вакансий
     * У сохраненного поиска можно изменить имя (&#x60;name&#x60;) и статус подписки (&#x60;subscription&#x60;). В одном запросе можно передать только один из параметров
     *
     * @param id Идентификатор сохраненного поиска (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param name Новое имя сохраненного поиска (optional)
     * @param subscription Статус подписки (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка в параметре запроса (status code 400)
     *         or Ошибка авторизации пользователя (status code 403)
     *         or Не найдено или не доступно текущему пользователю (status code 404)
     *         or Ошибка запроса при одновременном изменении параметров (status code 409)
     */
    @Operation(
        operationId = "updateSavedVacancySearch",
        summary = "Обновление сохраненного поиска вакансий",
        description = "У сохраненного поиска можно изменить имя (`name`) и статус подписки (`subscription`). В одном запросе можно передать только один из параметров",
        tags = { "Сохраненные поиски вакансий" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка в параметре запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadArgumentErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации пользователя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Не найдено или не доступно текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            }),
            @ApiResponse(responseCode = "409", description = "Ошибка запроса при одновременном изменении параметров", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonConflictBothChangedErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/saved_searches/vacancies/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> updateSavedVacancySearch(
        @Parameter(name = "id", description = "Идентификатор сохраненного поиска", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "name", description = "Новое имя сохраненного поиска", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) String name,
        @Parameter(name = "subscription", description = "Статус подписки", in = ParameterIn.QUERY) @Valid @RequestParam(value = "subscription", required = false) Boolean subscription,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
