/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.brobrocode.cadra.client.model.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Подсказки", description = "Методы для получения справочной информации в виде списка, элементы которого частично или полностью могут совпадать со значением, отправленным в одном из параметров")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}")
public interface SuggestsApi {

    /**
     * GET /suggests/area_leaves : Подсказки по регионам, являющимися листами в дереве регионов
     * Также доступна загрузка [полного дерева регионов](#tag/Obshie-spravochniki/operation/get-areas) и [части дерева от определенного элемента](#tag/Obshie-spravochniki/operation/get-areas-from-specified)
     *
     * @param text Текст для поиска региона. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param areaId Идентификатор региона из [справочника](#tag/Obshie-spravochniki/operation/get-areas). Сужает подсказки поддеревом переданного идентификатора региона (optional)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getAreaLeavesSuggests",
        summary = "Подсказки по регионам, являющимися листами в дереве регионов",
        description = "Также доступна загрузка [полного дерева регионов](#tag/Obshie-spravochniki/operation/get-areas) и [части дерева от определенного элемента](#tag/Obshie-spravochniki/operation/get-areas-from-specified)",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsAreas.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/area_leaves",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsAreas> getAreaLeavesSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска региона. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "area_id", description = "Идентификатор региона из [справочника](#tag/Obshie-spravochniki/operation/get-areas). Сужает подсказки поддеревом переданного идентификатора региона", in = ParameterIn.QUERY) @Valid @RequestParam(value = "area_id", required = false) String areaId,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/areas : Подсказки по регионам
     * Также доступна загрузка [полного дерева регионов](#tag/Obshie-spravochniki/operation/get-areas) и [части дерева от определенного элемента](#tag/Obshie-spravochniki/operation/get-areas-from-specified)
     *
     * @param text Текст для поиска региона. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param areaId Идентификатор региона из [справочника](#tag/Obshie-spravochniki/operation/get-areas). Сужает подсказки поддеревом переданного идентификатора региона (optional)
     * @param includeParent Включать ли в ответ регион, переданный в параметре &#x60;area_id&#x60;, если он подходит по искомому тексту (optional, default to false)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getAreasSuggests",
        summary = "Подсказки по регионам",
        description = "Также доступна загрузка [полного дерева регионов](#tag/Obshie-spravochniki/operation/get-areas) и [части дерева от определенного элемента](#tag/Obshie-spravochniki/operation/get-areas-from-specified)",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsAreas.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/areas",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsAreas> getAreasSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска региона. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "area_id", description = "Идентификатор региона из [справочника](#tag/Obshie-spravochniki/operation/get-areas). Сужает подсказки поддеревом переданного идентификатора региона", in = ParameterIn.QUERY) @Valid @RequestParam(value = "area_id", required = false) String areaId,
        @Parameter(name = "include_parent", description = "Включать ли в ответ регион, переданный в параметре `area_id`, если он подходит по искомому тексту", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_parent", required = false, defaultValue = "false") Boolean includeParent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/educational_institutions : Подсказки по названиям учебных заведений
     * Чтобы узнать список факультетов, обратитесь к [соответствующему методу](#tag/Obshie-spravochniki/operation/get-educational-institutions-dictionary)
     *
     * @param text Текст для поиска учебного заведения. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getEducationalInstitutionsSuggests",
        summary = "Подсказки по названиям учебных заведений",
        description = "Чтобы узнать список факультетов, обратитесь к [соответствующему методу](#tag/Obshie-spravochniki/operation/get-educational-institutions-dictionary)",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsEducationalInstitutions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/educational_institutions",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsEducationalInstitutions> getEducationalInstitutionsSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска учебного заведения. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/fields_of_study : Подсказки по специализациям
     *
     * @param text Текст для поиска специализаций. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getFieldsOfStudySuggestions",
        summary = "Подсказки по специализациям",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsFieldsOfStudy.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/fields_of_study",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsFieldsOfStudy> getFieldsOfStudySuggestions(
        @NotNull @Parameter(name = "text", description = "Текст для поиска специализаций. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/positions : Подсказки по должностям резюме
     *
     * @param text Текст для поиска должности. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getPositionsSuggestions",
        summary = "Подсказки по должностям резюме",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsPositions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/positions",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsPositions> getPositionsSuggestions(
        @NotNull @Parameter(name = "text", description = "Текст для поиска должности. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/professional_roles : Подсказки по профессиональным ролям
     *
     * @param text Текст для поиска профессиональной роли. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getProfessionalRolesSuggests",
        summary = "Подсказки по профессиональным ролям",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsProfessionalRoles.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/professional_roles",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsProfessionalRoles> getProfessionalRolesSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска профессиональной роли. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/companies : Подсказки по зарегистрированным организациям
     * Данные из этой подсказки можно использовать, например, для выбора компании при заполнении опыта работы [в резюме](#tag/Rezyume.-Sozdanie-i-obnovlenie). Чтобы найти организации, которые могут публиковать вакансии, используйте [поиск](#tag/Rabotodatel/operation/search-employer)
     *
     * @param text Текст для поиска организации. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getRegisteredCompaniesSuggests",
        summary = "Подсказки по зарегистрированным организациям",
        description = "Данные из этой подсказки можно использовать, например, для выбора компании при заполнении опыта работы [в резюме](#tag/Rezyume.-Sozdanie-i-obnovlenie). Чтобы найти организации, которые могут публиковать вакансии, используйте [поиск](#tag/Rabotodatel/operation/search-employer)",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsCompanies.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/companies",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsCompanies> getRegisteredCompaniesSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска организации. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/resume_search_keyword : Подсказки по ключевым словам поиска резюме
     * Предназначены для использования в поле &#x60;text&#x60; при [поиске резюме](#tag/Poisk-rezyume/operation/search-for-resumes). Содержит названия должностей, компаний и другие фразы, часто используемые при поиске резюме
     *
     * @param text Текст для поиска ключевого слова. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getResumeSearchKeywordsSuggests",
        summary = "Подсказки по ключевым словам поиска резюме",
        description = "Предназначены для использования в поле `text` при [поиске резюме](#tag/Poisk-rezyume/operation/search-for-resumes). Содержит названия должностей, компаний и другие фразы, часто используемые при поиске резюме",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsSearchKeyword.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/resume_search_keyword",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsSearchKeyword> getResumeSearchKeywordsSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска ключевого слова. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/skill_set : Подсказки по ключевым навыкам
     *
     * @param text Текст для поиска ключевых навыков. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getSkillSetSuggests",
        summary = "Подсказки по ключевым навыкам",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsSkillSet.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/skill_set",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsSkillSet> getSkillSetSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска ключевых навыков. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/vacancy_positions : Подсказки по должностям вакансий
     *
     * @param text Текст для поиска должности в вакансии. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getVacancyPositionsSuggests",
        summary = "Подсказки по должностям вакансий",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsVacancyPositions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/vacancy_positions",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsVacancyPositions> getVacancyPositionsSuggests(
        @NotNull @Parameter(name = "text", description = "Текст для поиска должности в вакансии. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /suggests/vacancy_search_keyword : Подсказки по ключевым словам поиска вакансий
     * Предназначены для использования в поле &#x60;text&#x60; при [поиске вакансий](#tag/Poisk-vakansij/operation/get-vacancies). Содержит названия должностей, компаний и другие фразы, часто используемые при поиске вакансий
     *
     * @param text Текст для поиска ключевого слова. Искомый текст должен быть длиной два или более символа и не более 3 000 символов (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Ошибки запроса (status code 400)
     */
    @Operation(
        operationId = "getVacancySearchKeywords",
        summary = "Подсказки по ключевым словам поиска вакансий",
        description = "Предназначены для использования в поле `text` при [поиске вакансий](#tag/Poisk-vakansij/operation/get-vacancies). Содержит названия должностей, компаний и другие фразы, часто используемые при поиске вакансий",
        tags = { "Подсказки" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsSearchKeyword.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибки запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SuggestsErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/suggests/vacancy_search_keyword",
        produces = { "application/json" }
    )
    
    ResponseEntity<SuggestsSearchKeyword> getVacancySearchKeywords(
        @NotNull @Parameter(name = "text", description = "Текст для поиска ключевого слова. Искомый текст должен быть длиной два или более символа и не более 3 000 символов", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "text", required = true) String text,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
