/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ru.brobrocode.cadra.client.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import ru.brobrocode.cadra.client.model.*;

import ru.brobrocode.cadra.client.config.HhApiFeignConfiguration;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-08-17T15:41:09.394389505+05:00[Asia/Yekaterinburg]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Webhook API", description = "Методы для управления подписками на уведомления. Описание полей колбэков находится в разделе [Callbacks](#callbacks) ")
@FeignClient(name = "hh-api", url = "${hh.api.base-url}", configuration = HhApiFeignConfiguration.class)
public interface WebhookApi {

    /**
     * DELETE /webhook/subscriptions/{subscription_id} : Удалить подписку на уведомление
     *
     * @param subscriptionId Идентификатор подписки (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка авторизации (status code 403)
     *         or Подписка не найдена или недоступна текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "cancelWebhookSubscription",
        summary = "Удалить подписку на уведомление",
        tags = { "Webhook API", "Управление подписками на Webhook" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "403", description = "Ошибка авторизации", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Подписка не найдена или недоступна текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/webhook/subscriptions/{subscription_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> cancelWebhookSubscription(
        @Parameter(name = "subscription_id", description = "Идентификатор подписки", required = true, in = ParameterIn.PATH) @PathVariable("subscription_id") String subscriptionId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * PUT /webhook/subscriptions/{subscription_id} : Изменить подписку на уведомления
     * Обновить можно как каждое поле по отдельности (в таком случае нужно отправить только обновляемое поле), так и несколько полей одновременно. Для обновления &#x60;actions&#x60; нужно передать полный список типов событий, по которым будут формироваться уведомления. Переданные типы событий не добавляются к типам событий, на которые пользователь уже подписан. Пустой список &#x60;actions&#x60; передать нельзя 
     *
     * @param subscriptionId Идентификатор подписки (required)
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param webhookSubscriptionUpdate  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 204)
     *         or Ошибка параметров запроса (status code 400)
     *         or Запрос выполнен не с авторизацией работодателя (status code 403)
     *         or Подписка не найдена или недоступна текущему пользователю (status code 404)
     */
    @Operation(
        operationId = "changeWebhookSubscription",
        summary = "Изменить подписку на уведомления",
        description = "Обновить можно как каждое поле по отдельности (в таком случае нужно отправить только обновляемое поле), так и несколько полей одновременно. Для обновления `actions` нужно передать полный список типов событий, по которым будут формироваться уведомления. Переданные типы событий не добавляются к типам событий, на которые пользователь уже подписан. Пустой список `actions` передать нельзя ",
        tags = { "Webhook API" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Успешный ответ"),
            @ApiResponse(responseCode = "400", description = "Ошибка параметров запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadJsonDataErrors.class))
            }),
            @ApiResponse(responseCode = "403", description = "Запрос выполнен не с авторизацией работодателя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            }),
            @ApiResponse(responseCode = "404", description = "Подписка не найдена или недоступна текущему пользователю", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonNotFoundErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/webhook/subscriptions/{subscription_id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> changeWebhookSubscription(
        @Parameter(name = "subscription_id", description = "Идентификатор подписки", required = true, in = ParameterIn.PATH) @PathVariable("subscription_id") String subscriptionId,
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "WebhookSubscriptionUpdate", description = "", required = true) @Valid @RequestBody WebhookSubscriptionUpdate webhookSubscriptionUpdate,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * GET /webhook/subscriptions : Получить список уведомлений, на которые подписан пользователь
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешный ответ (status code 200)
     *         or Запрос выполнен не с авторизацией работодателя (status code 403)
     */
    @Operation(
        operationId = "getWebhookSubscriptions",
        summary = "Получить список уведомлений, на которые подписан пользователь",
        tags = { "Webhook API" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Успешный ответ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WebhookSubscriptionsOutput.class))
            }),
            @ApiResponse(responseCode = "403", description = "Запрос выполнен не с авторизацией работодателя", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/webhook/subscriptions",
        produces = { "application/json" }
    )
    
    ResponseEntity<WebhookSubscriptionsOutput> getWebhookSubscriptions(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );


    /**
     * POST /webhook/subscriptions : Подписаться на уведомления
     * В рамках одного приложения пользователь может получать уведомления только на 1 url:   нельзя подписаться разными действиями на разные урлы. После наступления события будет отправлен POST-запрос на указанный URL c json телом (**см. раздел \&quot;Callbacks\&quot;**).   В ответ на POST-запрос ожидается ответ с кодом &#x60;2хх Success&#x60;, если сообщение принято, или &#x60;409 Conflict&#x60;, если пришел дубликат.  Для определения дубликатов нужно использовать id из запроса - уникальный идентификатор для пары \&quot;пользователь + приложение\&quot; в рамках одного типа события в подписке.   Дубликаты возможны, если: * url, на который отправлялся колбэк, не ответил в течение 2 секунд; * сервер не смог установить соединение с url, на который необходимо отправить колбэк; * url ответил неожиданным кодом (отличным от &#x60;2xx Success&#x60; или &#x60;409 Conflict&#x60;)  В этих случаях сервер планирует повторную отправку колбэка, с постепенно увеличивающимся промежутком между переотправками.  Если в рамках одной подписки ожидаемые ответы не поступают долгое время,  на почту разработчика приложения будет отправлено уведомительное письмо, подписка попадает в очередь на блокировку, а отправки прекращаются.   Если до блокировки приложения в рамках подписки url ответит ожидаемым кодом в установленный таймаут, подписка исключается из очереди на блокировку.  При удалении приложения владельцем или отзыве пользователем доступа у приложения все подписки на уведомления удаляются.  После восстановления доступа необходимо оформить новую подписку.   Вебхуки не являются средствами гарантированной доставки. Мы отправляем все сообщения, но не гарантируем, что адресат их получит  Структура и содержимое колбэков описаны в разделе [callbacks](#callbacks) 
     *
     * @param hhUserAgent Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam))  (required)
     * @param webhookSubscriptionCreate  (required)
     * @param locale Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales))  (optional, default to RU)
     * @param host Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta))  (optional, default to hh.ru)
     * @return Успешно создано (status code 201)
     *         or Ошибка параметров запроса (status code 400)
     *         or Запрос &lt;a name&#x3D;\&quot;callbacks\&quot;&gt;&lt;/a&gt; не от работодателя  (status code 403)
     */
    @Operation(
        operationId = "postWebhookSubscription",
        summary = "Подписаться на уведомления",
        description = "В рамках одного приложения пользователь может получать уведомления только на 1 url:   нельзя подписаться разными действиями на разные урлы. После наступления события будет отправлен POST-запрос на указанный URL c json телом (**см. раздел \"Callbacks\"**).   В ответ на POST-запрос ожидается ответ с кодом `2хх Success`, если сообщение принято, или `409 Conflict`, если пришел дубликат.  Для определения дубликатов нужно использовать id из запроса - уникальный идентификатор для пары \"пользователь + приложение\" в рамках одного типа события в подписке.   Дубликаты возможны, если: * url, на который отправлялся колбэк, не ответил в течение 2 секунд; * сервер не смог установить соединение с url, на который необходимо отправить колбэк; * url ответил неожиданным кодом (отличным от `2xx Success` или `409 Conflict`)  В этих случаях сервер планирует повторную отправку колбэка, с постепенно увеличивающимся промежутком между переотправками.  Если в рамках одной подписки ожидаемые ответы не поступают долгое время,  на почту разработчика приложения будет отправлено уведомительное письмо, подписка попадает в очередь на блокировку, а отправки прекращаются.   Если до блокировки приложения в рамках подписки url ответит ожидаемым кодом в установленный таймаут, подписка исключается из очереди на блокировку.  При удалении приложения владельцем или отзыве пользователем доступа у приложения все подписки на уведомления удаляются.  После восстановления доступа необходимо оформить новую подписку.   Вебхуки не являются средствами гарантированной доставки. Мы отправляем все сообщения, но не гарантируем, что адресат их получит  Структура и содержимое колбэков описаны в разделе [callbacks](#callbacks) ",
        tags = { "Webhook API" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Успешно создано", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Id.class))
            }),
            @ApiResponse(responseCode = "400", description = "Ошибка параметров запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WebhookBadDataError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Запрос <a name=\"callbacks\"></a> не от работодателя ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorsCommonBadAuthorizationErrors.class))
            })
        },
        security = {
            @SecurityRequirement(name = "OauthToken")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/webhook/subscriptions",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Id> postWebhookSubscription(
        @NotNull @Parameter(name = "HH-User-Agent", description = "Название приложения и контактная почта разработчика (см. [Информация о клиенте](#section/Obshaya-informaciya/Trebovaniya-k-zaprosam)) ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "HH-User-Agent", required = true) String hhUserAgent,
        @Parameter(name = "WebhookSubscriptionCreate", description = "", required = true) @Valid @RequestBody WebhookSubscriptionCreate webhookSubscriptionCreate,
        @Parameter(name = "locale", description = "Идентификатор локали (см. [Локализация](#tag/Obshie-spravochniki/operation/get-locales)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "locale", required = false, defaultValue = "RU") String locale,
        @Parameter(name = "host", description = "Доменное имя сайта (см. [Выбор сайта](#section/Obshaya-informaciya/Vybor-sajta)) ", in = ParameterIn.QUERY) @Valid @RequestParam(value = "host", required = false, defaultValue = "hh.ru") String host
    );

}
